<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'5YWz5LqO5oiR5Lus');
$cfg_Cs[2]=array(0,1,1,'5YWs5Y+45Yqo5oCB');
$cfg_Cs[3]=array(0,1,1,'5Lqn5ZOB5bGV56S6');
$cfg_Cs[4]=array(0,1,1,'5Y6C5oi/6K6+5aSH');
$cfg_Cs[5]=array(0,1,1,'5oiQ5Yqf5qGI5L6L');
$cfg_Cs[6]=array(0,1,1,'6I2j6KqJ6LWE6LSo');
$cfg_Cs[7]=array(0,1,1,'6IGU57O75oiR5Lus');
$cfg_Cs[8]=array(3,1,1,'5Yay5a2U572R');
$cfg_Cs[9]=array(3,1,1,'5Yay5a2U5p2/');
$cfg_Cs[10]=array(3,1,1,'5Yay5a2U5p2/5Zu05oyh');
$cfg_Cs[11]=array(0,1,1,'5bm754Gv54mH77yIcGPnq6/vvIk=');
$cfg_Cs[12]=array(0,1,1,'5bm754Gv54mH77yId2Fw56uv77yJ');
?>