<?php
$typeArr[1] = '关于我们';
$typeArr[2] = '企业文化';
$typeArr[4] = '公司资质';
$typeArr[5] = '产品中心';
$typeArr[6] = '传统烘干系列';
$typeArr[7] = '模内干燥系列';
$typeArr[8] = '纸浆模塑系列';
$typeArr[9] = '新闻中心';
$typeArr[10] = '公司资讯';
$typeArr[11] = '行业动态';
$typeArr[12] = '合作案例';
$typeArr[3] = '企业风采';
$typeArr[13] = '在线留言';
$typeArr[14] = '联系我们';
$typeArr[15] = '售后承诺';
$typeArr[29] = '品质坚持';
$typeArr[30] = '安全保障';
$typeArr[33] = '维护方便';
$typeArr[32] = '绿色环保';
$typeArr[31] = '贴心设计';
$typeArr[28] = '常见问题';
$typeArr[27] = '产品优势';
$typeArr[34] = '节能省电';
$typeArr[35] = '舒适健康';
$typeArr[36] = '完善服务';
?>