<?php
$z[0]=Array("field","",159,187);
$z[0][4]=array();
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",196,225);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("field","",227,256);
$z[2][4]=array();
$z[2][4]['name']="typename";
$z[3]=Array("arclist","\r\n		  <li><a href=\"[field:arcurl/]\" title=\"[field:title/]\"><img src=\"[field:litpic/]\" alt=\"[field:title/]\">\r\n            <p >[field:title/]</p>\r\n            </a></li>\r\n			",382,633);
$z[3][4]=array();
$z[3][4]['typeid']="";
$z[3][4]['row']="10";
$z[3][4]['titlelen']="50";
$z[3][4]['orderby']="pubdate";

?>