<?php
$z[0]=Array("field","",125,153);
$z[0][4]=array();
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",162,191);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("field","",193,222);
$z[2][4]=array();
$z[2][4]['name']="typename";
$z[3]=Array("arclist","\r\n		<li><a href=\"[field:arcurl/]\" title=\"[field:title/]\">\r\n          <div class=\"xwtp\"><img src=\"[field:litpic/]\" alt=\"[field:title/]\"></div>\r\n          <div class=\"xwwz\">\r\n            <h3 >[field:title/]</h3>\r\n            <p>[field:description function=\"cn_substr(@me,200)\"/]...</p>\r\n            <span>[查看详情]</span></div>\r\n          </a></li>\r\n		  ",254,690);
$z[3][4]=array();
$z[3][4]['typeid']="";
$z[3][4]['row']="3";
$z[3][4]['titlelen']="50";
$z[3][4]['orderby']="pubdate";

?>