<!--产品展示开始-->
<div class="i_pro_bg2">
    <div class="wp1">
        <div class="in_pro_title anim anim-1"><b>PRODUCTS</b><a href="/a/chanpinzhongxin/" title="产品中心">产品中心</a></div>
        <div id="owl-demo2" class="owl-carousel anim anim-2">
            <div class="item">
                <dd class="not-animated"><a href="/a/chanpinzhongxin/langmanxilie/33.html" title="最新法式轻奢风顶层复">
                    <div class="imgs"><img src="/uploads/allimg/210609/1-21060Z934500-L.jpg" alt="最新法式轻奢风顶层复"></div>
                    <h3>最新法式轻奢风顶层复
                        <p>这个家的男主人是一名独立手表品牌主理人，喜欢机械的理性和艺术的感性；同时也会将夫妻喜爱的黑胶唱片和书籍收纳起来。这个家庭追求精神的契合，...</p>
                    </h3>
                    </a></dd>
            </div>
            <div class="item">
                <dd class="not-animated"><a href="/a/chanpinzhongxin/langmanxilie/32.html" title="凯景中央10栋95平15万全包">
                    <div class="imgs"><img src="/uploads/allimg/210609/1-21060Z934060-L.jpg" alt="凯景中央10栋95平15万全包"></div>
                    <h3>凯景中央10栋95平15万全包
                        <p>屋主特别喜欢线条感，所以从客餐厅到卧室，都能看到层次丰富，细腻而精致的线条。设计师选择了硬度更好的PU线条，清晰度更好，细节感也很强。谁说...</p>
                    </h3>
                    </a></dd>
            </div>
            <div class="item">
                <dd class="not-animated"><a href="/a/chanpinzhongxin/langmanxilie/31.html" title="槎窖公寓150现代无主灯">
                    <div class="imgs"><img src="/uploads/allimg/210609/1-21060Z933140-L.jpg" alt="槎窖公寓150现代无主灯"></div>
                    <h3>槎窖公寓150现代无主灯
                        <p>自然总是在不经意间和人类达成默契，我们从蜂巢的建构中获得灵感，看到这其乐融融的一家人，让人联想到勤劳的蜜蜂筑起爱巢的意象。我们也想为客户...</p>
                    </h3>
                    </a></dd>
            </div>
            <div class="item">
                <dd class="not-animated"><a href="/a/chanpinzhongxin/xinguixilie/30.html" title="东方家园100平 法式">
                    <div class="imgs"><img src="/uploads/allimg/210609/1-21060Z932180-L.jpg" alt="东方家园100平 法式"></div>
                    <h3>东方家园100平 法式
                        <p>房子建筑面积有111㎡，实用面积95㎡。为了隐形扩容，设计师在主卧和客卧都做了飘窗储物设计。书房属于半卖半送带了一个小阳台，装修时直接拆掉墙体...</p>
                    </h3>
                    </a></dd>
            </div>
            <div class="item">
                <dd class="not-animated"><a href="/a/chanpinzhongxin/xinguixilie/29.html" title="世茂石湖湾+现代简约">
                    <div class="imgs"><img src="/uploads/allimg/210609/1-21060Z931290-L.jpg" alt="世茂石湖湾+现代简约"></div>
                    <h3>世茂石湖湾+现代简约
                        <p>现代简约，装饰空间。揽月而居，象湖顶跃，诠释现代质感。本案例是一套精装房改造，在硬装上没有做多大的改动，主要以软装来改造空间，色调上，使...</p>
                    </h3>
                    </a></dd>
            </div>
            <div class="item">
                <dd class="not-animated"><a href="/a/chanpinzhongxin/huangjiaxilie/28.html" title="金地自在城 现代效果图">
                    <div class="imgs"><img src="/uploads/allimg/210609/1-21060Z930150-L.jpg" alt="金地自在城 现代效果图"></div>
                    <h3>金地自在城 现代效果图
                        <p>说到改造，各类案例都会选择改动户型、调整布局，大张旗鼓从硬装着手。但户型不好动的痛苦，又有谁知道！今天的神仙屋主，就是被户型硬从装修小白...</p>
                    </h3>
                    </a></dd>
            </div>
            <div class="item">
                <dd class="not-animated"><a href="/a/chanpinzhongxin/huangjiaxilie/27.html" title="鸥鹏御府 现代效果图">
                    <div class="imgs"><img src="/uploads/allimg/210609/1-21060Z929310-L.jpg" alt="鸥鹏御府 现代效果图"></div>
                    <h3>鸥鹏御府 现代效果图
                        <p>简欧风格就是简化了的欧式装修风格。也是住宅别墅装修最流行的风格。简欧风格更多的表现为实用性和多元化。简欧家具包括床、电视柜、书柜、衣柜、...</p>
                    </h3>
                    </a></dd>
            </div>
            <div class="item">
                <dd class="not-animated"><a href="/a/chanpinzhongxin/huangjiaxilie/26.html" title="贝蒙新湖 北欧效果图">
                    <div class="imgs"><img src="/uploads/allimg/210609/1-21060Z92S30-L.jpg" alt="贝蒙新湖 北欧效果图"></div>
                    <h3>贝蒙新湖 北欧效果图
                        <p>现代轻奢风格，让小3房户型得意高度利用的同时，保持客厅应有的宽阔通透。轻奢风格的家具让您再不大的户型里也能享受五星级酒店般的奢华与舒适，不...</p>
                    </h3>
                    </a></dd>
            </div>
            <div class="item">
                <dd class="not-animated"><a href="/a/chanpinzhongxin/huangjiaxilie/25.html" title="昱湖壹号 现代混搭效果图">
                    <div class="imgs"><img src="/uploads/allimg/210609/1-21060Z923070-L.jpg" alt="昱湖壹号 现代混搭效果图"></div>
                    <h3>昱湖壹号 现代混搭效果图
                        <p>眼帘间蓊郁青翠的山峦，树海如盖，风从树梢之间轻盈地溜过，引起翻涌如浪涛般的飒响。恍惚之间，你也游进了这片森林树海，就像小时候爬过的那些树...</p>
                    </h3>
                    </a></dd>
            </div>
        </div>
        <script src="/skin/js/owl.carousel.js" ></script>
        <script>
        $("#owl-demo2").owlCarousel({
            items: 2,
            lazyLoad: true,
            autoPlay: true,
            itemsDesktop: [1199, 2],
            itemsDesktopSmall: [979, 2],
            itemsTablet: [768, 2],
            itemsTabletSmall: false,
            itemsMobile: [479, 1],
            navigation: true
        });
</script>
    </div>
</div>
<!--产品展示结束-->