<?php
$z[0]=Array("pubdate","",38,81);
$z[0][4]=array();
$z[0][4]['function']="MyDate('d',@me)";
$z[1]=Array("pubdate","",103,148);
$z[1][4]=array();
$z[1][4]['function']="MyDate('Y-m',@me)";
$z[2]=Array("arcurl","",188,203);
$z[2][4]=array();
$z[3]=Array("title","",212,226);
$z[3][4]=array();
$z[4]=Array("title","",228,242);
$z[4][4]=array();
$z[5]=Array("description","",264,314);
$z[5][4]=array();
$z[5][4]['function']="cn_substr(@me,120)";

?>