<?php
$z[0]=Array("field","",105,134);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("field","",157,189);
$z[1][4]=array();
$z[1][4]['name']="description";
$z[2]=Array("arclist","\r\n		<li><a href=\"view.php?aid=[field:title/]\" title=\"[field:title/]\"><img src=\"[field:litpic/]\" alt=\"[field:title/]\">\r\n          <div class=\"tl\"><em >[field:title/]</em>\r\n            <p>[field:description function=\"cn_substr(@me,80)\"/]...</p>\r\n            <span>阅读数：[field:click/]</span><i>日期：[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</i></div>\r\n          </a></li>\r\n		  ",262,722);
$z[2][4]=array();
$z[2][4]['row']="5";
$z[2][4]['titlelen']="50";
$z[2][4]['orderby']="pubdate";
$z[3]=Array("field","",802,825);
$z[3][4]=array();
$z[3][4]['name']="id";

?>