<?php
$z[0]=Array("field","",89,118);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("channel","\r\n      <dd><a href=\"list.php?tid=[field:id/]\" title=\"[field:typename/]\">[field:typename/]</a></dd>\r\n	  ",247,392);
$z[1][4]=array();
$z[1][4]['type']="top";
$z[2]=Array("arclist","\r\n		  <div class=\"swiper-slide\"><a href=\"view.php?aid=[field:id/]\" title=\"[field:title/]\">\r\n          <div class=\"img\"><img src=\"[field:litpic/]\" alt=\"[field:title/]\"></div>\r\n          <h3>[field:title/]</h3>\r\n          <p class=\"cont\">[field:description/]...</p>\r\n          </a></div>\r\n        ",558,931);
$z[2][4]=array();
$z[2][4]['row']="6";
$z[2][4]['titlelen']="60";
$z[2][4]['orderby']="pubdate";
$z[2][4]['flag']="h";
$z[3]=Array("global","",2010,2032);
$z[3][4]=array();
$z[3][4]['name']="cfg_tel";

?>