<dd class="d[field:global runphp='yes' name=autoindex][/field:global]">
              <div class="box1"><a href="[field:arcurl/]" title="[field:title/]">
                <h3>[field:title/]</h3>
                <p>产品以再生废纸、芦苇浆、甘蔗浆、植物桔杆、果壳等为原料,可完全回收再生利用。~再生废纸、植物桔杆等为原料 产品原料和成品弃置后...</p>
                <i class="icon"></i><span class="icon"></span></a></div>
              <div class="box2"><a href="[field:arcurl/]" title="[field:title/]"><img src="[field:litpic/]" alt="[field:title/]"></a></div>
            </dd>