














































<field:titles itemname="留言标题" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:titles>

<field:name itemname="你的姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:name>

<field:tel itemname="联系电话" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:tel>

<field:email itemname="电子邮箱" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:email>

<field:address itemname="联系地址" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:address>

<field:yuanwang itemname="留言内容" autofield="1" type="multitext" isnull="true" default=""  maxlength="250" page="">
</field:yuanwang>
