<li class="item" [field:global runphp='yes' name=autoindex]
                      $a="style='margin-right:0;'";
                        $b="";
                        if ((@me%3)==0 && @me!=15)  @me=$a;
                        else  @me=$b;
                        [/field:global]><a href="[field:arcurl/]" title="[field:title/]"><img src="[field:litpic/]" alt="[field:title/]">
            <div class="item_mask">
              <div class="item_link_icon ico"></div>
            </div>
            <span >[field:title/]</span></a></li>