<?php
$z[0]=Array("field","",193,224);
$z[0][4]=array();
$z[0][4]['name']="typenameen";
$z[1]=Array("field","",254,283);
$z[1][4]=array();
$z[1][4]['name']="seotitle";
$z[2]=Array("sql"," \r\n        [field:content  function='cn_substr(html2text(@me),500)'/]\r\n        ",328,478);
$z[2][4]=array();
$z[2][4]['sql']="Select content from dede_arctype where id=1";
$z[3]=Array("field","",508,536);
$z[3][4]=array();
$z[3][4]['name']="typeurl";

?>