<?php
$z[0]=Array("field","",159,187);
$z[0][4]=array();
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",196,225);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("field","",227,256);
$z[2][4]=array();
$z[2][4]['name']="typename";
$z[3]=Array("field","",373,401);
$z[3][4]=array();
$z[3][4]['name']="typeimg";
$z[4]=Array("field","",408,437);
$z[4][4]=array();
$z[4][4]['name']="typename";
$z[5]=Array("sql"," \r\n        [field:content  function='cn_substr(html2text(@me),1000)'/]\r\n        ",566,717);
$z[5][4]=array();
$z[5][4]['sql']="Select content from dede_arctype where id=1";
$z[6]=Array("field","",748,776);
$z[6][4]=array();
$z[6][4]['name']="typeurl";

?>