<div class="in_news_t anim anim-1">
            <div class="in_news_t_l"><a href="[field:arcurl/]" title="[field:fulltitle/]" class="img"><img src="[field:litpic/]" alt="[field:fulltitle/]"></a></div>
            <div class="in_news_t_r"><a href="[field:arcurl/]" title="[field:fulltitle/]">[field:title/]</a><span>[field:pubdate function="MyDate('Y-m-d',@me)"/]</span>
                <p>[field:description/]...</p>
                <h3><a href="[field:arcurl/]">READ MORE +</a></h3>
            </div>
        </div>
        <!--推荐内容结束-->