<?php
$z[0]=Array("field","",179,208);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("field","",243,275);
$z[1][4]=array();
$z[1][4]['name']="description";
$z[2]=Array("arclist","\r\n					<div class=\"col-sm-4 col-md-3 col-mm-6 case_img\" data-move-y=\"50px\">\r\n						<a href=\"[field:arcurl/]\"><img src=\"[field:litpic/]\" class=\"opacity_img\" alt=\"[field:title/]\"/></a>\r\n						<p class=\"case_title\">\r\n							<a href=\"[field:arcurl/]\">[field:title/]</a>\r\n						</p>\r\n					</div>\r\n					",327,703);
$z[2][4]=array();
$z[2][4]['typeid']="";
$z[2][4]['row']="4";
$z[2][4]['titlelen']="50";
$z[2][4]['orderby']="pubdate";

?>