<div id="floor_2_main">
    <div class="floor_2 w1200">
      <div class="in_title clearfix" aos="fade-up" aos-easing="ease" aos-duration="700">
        <p class="entit" aos="fade-up" aos-easing="ease" aos-duration="700">{dede:field name='typenameen'/}</p>
        <h3 class="tit clearfix" aos="fade-up" aos-easing="ease" aos-duration="700" aos-delay="100"><em class="line"></em><span class="word">{dede:field name='typename'/}</span><em class="line"></em></h3>
      </div>
      <!--产品分类开始-->
      <div class="tab" aos="fade-up" aos-easing="ease" aos-duration="700" aos-delay="200">  <a href="/a/chanpinzhongxin/cp1/" title="钢结构岗亭">钢结构岗亭</a> <a href="/a/chanpinzhongxin/cp2/" title="不锈钢岗亭">不锈钢岗亭</a> <a href="/a/chanpinzhongxin/cp3/" title="镀锌板岗亭">镀锌板岗亭</a> <a href="/a/chanpinzhongxin/cp4/" title="金属雕花板岗">金属雕花板岗</a> <a href="/a/chanpinzhongxin/cp5/" title="防腐木岗亭">防腐木岗亭</a> <a href="/a/chanpinzhongxin/cp6/" title="铝塑板岗亭">铝塑板岗亭</a></div>
      <!--产品分类结束-->
      <div class="proCenter" aos="fade-up" aos-easing="ease" aos-duration="700" aos-delay="200">
        <ul class="list clearfix">
          <li><a href="/a/chanpinzhongxin/cp2/39.html" title="产品中心标题九"><img src="/uploads/allimg/191106/1-1911061F9430-L.jpg" alt="产品中心标题九"/>
            <div class="title clearfix">
              <h3 class="tit" >产品中心标题九</h3>
            </div>
            </a></li>
<li><a href="/a/chanpinzhongxin/cp2/38.html" title="产品中心标题八"><img src="/uploads/allimg/191106/1-1911061FZ90-L.jpg" alt="产品中心标题八"/>
            <div class="title clearfix">
              <h3 class="tit" >产品中心标题八</h3>
            </div>
            </a></li>
<li><a href="/a/chanpinzhongxin/cp2/37.html" title="产品中心标题七"><img src="/uploads/allimg/191106/1-1911061FP60-L.jpg" alt="产品中心标题七"/>
            <div class="title clearfix">
              <h3 class="tit" >产品中心标题七</h3>
            </div>
            </a></li>
<li><a href="/a/chanpinzhongxin/cp1/18.html" title="产品中心标题六"><img src="/uploads/allimg/190109/1-1Z10ZU3150-L.jpg" alt="产品中心标题六"/>
            <div class="title clearfix">
              <h3 class="tit" >产品中心标题六</h3>
            </div>
            </a></li>
<li><a href="/a/chanpinzhongxin/cp1/17.html" title="产品中心标题五"><img src="/uploads/allimg/190109/1-1Z10ZU2400-L.jpg" alt="产品中心标题五"/>
            <div class="title clearfix">
              <h3 class="tit" >产品中心标题五</h3>
            </div>
            </a></li>
<li><a href="/a/chanpinzhongxin/cp1/16.html" title="产品中心标题四"><img src="/uploads/allimg/190109/1-1Z10ZU2190-L.jpg" alt="产品中心标题四"/>
            <div class="title clearfix">
              <h3 class="tit" >产品中心标题四</h3>
            </div>
            </a></li>
<li><a href="/a/chanpinzhongxin/cp1/15.html" title="产品中心标题三"><img src="/uploads/allimg/190109/1-1Z10ZU1310-L.jpg" alt="产品中心标题三"/>
            <div class="title clearfix">
              <h3 class="tit" >产品中心标题三</h3>
            </div>
            </a></li>
<li><a href="/a/chanpinzhongxin/cp1/14.html" title="产品中心标题二"><img src="/uploads/allimg/190109/1-1Z10ZT9470-L.jpg" alt="产品中心标题二"/>
            <div class="title clearfix">
              <h3 class="tit" >产品中心标题二</h3>
            </div>
            </a></li>

        </ul>
      </div>
      <div class="more clearfix" aos="fade-up" aos-easing="ease" aos-duration="700">
        <div class="line fl"></div>
        <a class="look_more fl" href="/a/chanpinzhongxin/" title="查看更多>>">查看更多>></a>
        <div class="line fl"></div>
      </div>
    </div>
  </div>