<?php
$z[0]=Array("field","",42,70);
$z[0][4]=array();
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",79,108);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("field","",110,139);
$z[2][4]=array();
$z[2][4]['name']="typename";
$z[3]=Array("channel","\r\n          <dd><a href=\"[field:typelink/]\" title=\"[field:typename/]\">[field:typename/]</a></dd>\r\n          ",160,321);
$z[3][4]=array();
$z[3][4]['type']="son";
$z[3][4]['noself']="yes";

?>