<li class="item clearfix"><a href="[field:arcurl/]" title="[field:title/]"><img class="fl" src="[field:picname/]" alt="[field:title/]">
        <div class="time fr"><span class="day">[field:pubdate function="MyDate('m-d',@me)"/]</span><span>[field:pubdate function="MyDate('Y',@me)"/]</span></div>
        <h3>[field:title/]</h3>
        <div class="txt">[field:description function="cn_substr(@me,200)"/]...</div>
        </a></li>