<?php
$z[0]=Array("field","",11,37);
$z[0][4]=array();
$z[0][4]['name']="currentstyle";
$z[1]=Array("field","",48,76);
$z[1][4]=array();
$z[1][4]['name']="typeurl";
$z[2]=Array("field","",85,114);
$z[2][4]=array();
$z[2][4]['name']="typename";
$z[3]=Array("field","",116,145);
$z[3][4]=array();
$z[3][4]['name']="typename";
$z[4]=Array("channel","\r\n          <dd><a href=\"[field:typelink/]\" title=\"[field:typename/]\">[field:typename/]</a></dd>\r\n          ",175,336);
$z[4][4]=array();
$z[4][4]['type']="son";
$z[4][4]['noself']="yes";

?>