<?php
$z[0]=Array("field","",192,221);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("arclist","\r\n			  <li class=\"item\"><a href=\"[field:arcurl/]\" title=\"[field:title/]\"><img src=\"[field:litpic/]\" alt=\"[field:title/]\"/>\r\n                <p>[field:title/]<i class=\"icon\"></i></p>\r\n                <div class=\"bg\"></div>\r\n                <div class=\"txtIco\"><s class=\"icon\"></s></div>\r\n                </a></li>\r\n				",468,856);
$z[1][4]=array();
$z[1][4]['row']="10";
$z[1][4]['titlelen']="60";
$z[1][4]['orderby']="pubdate";
$z[2]=Array("field","",963,991);
$z[2][4]=array();
$z[2][4]['name']="typeurl";

?>