<?php
$z[0]=Array("field","",179,208);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("field","",223,255);
$z[1][4]=array();
$z[1][4]['name']="description";
$z[2]=Array("arclist","\r\n					<div class=\"col-sm-6 col-md-6 news_col\">\r\n						<li><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a><span class='news_time2'><strong>[field:pubdate function=\"MyDate('d',@me)\"/]</strong><i>[field:pubdate function=\"MyDate('Y-m',@me)\"/]</i></span><br>\r\n						<em class='news_time2'> [field:description function=\"cn_substr(@me,120)\"/]...</em></li>\r\n					</div>\r\n					",327,795);
$z[2][4]=array();
$z[2][4]['typeid']="";
$z[2][4]['row']="6";
$z[2][4]['titlelen']="50";
$z[2][4]['orderby']="pubdate";

?>