<?php
$z[0]=Array("pubdate","",34,77);
$z[0][4]=array();
$z[0][4]['function']="MyDate('d',@me)";
$z[1]=Array("pubdate","",97,142);
$z[1][4]=array();
$z[1][4]['function']="MyDate('Y-m',@me)";
$z[2]=Array("arcurl","",178,193);
$z[2][4]=array();
$z[3]=Array("title","",202,216);
$z[3][4]=array();
$z[4]=Array("title","",218,232);
$z[4][4]=array();
$z[5]=Array("description","",252,302);
$z[5][4]=array();
$z[5][4]['function']="cn_substr(@me,120)";

?>