<?php
$z[0]=Array("arcurl","",13,28);
$z[0][4]=array();
$z[1]=Array("fulltitle","",38,56);
$z[1][4]=array();
$z[2]=Array("pubdate","",101,144);
$z[2][4]=array();
$z[2][4]['function']="MyDate('d',@me)";
$z[3]=Array("pubdate","",156,201);
$z[3][4]=array();
$z[3][4]['function']="MyDate('Y-m',@me)";
$z[4]=Array("title","",272,286);
$z[4][4]=array();
$z[5]=Array("description","",314,334);
$z[5][4]=array();

?>