<dl class="in_dl2">
                <dt><a href="{dede:field name=typeurl/}" title="{dede:field name=typename/}" class="img"><img src="{dede:field name=typeimg/}" alt="{dede:field name=typename/}"></a></dt>
                <dd><a href="{dede:field name=typeurl/}" title="{dede:field name=typename/}">{dede:field name=typename/}</a></dd>
                <dd>初步洽谈：公司简介、加盟条件、方式及要求、参观展厅。<BR>
          代理商甄选：经洽谈是否符合加盟标准。<BR>
          意向申请：指导意见加盟商做市场调查及计划书。<BR>
          店面确定：协助选择店面、落实是否签订租赁合同等。<BR>
          市场考察：市场情况、竞争对手等考察。<BR>
          公司评审：是否符合要求，人员是否到位、资金是否到位。<BR>
          意向签订：缴纳保证金、提交店面平面图、人员培训申请。<BR>
          签订协议：双方签订经销协议。
</dd>
			</dl>