<?php
$z[0]=Array("field","",179,208);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("arclist","\r\n		   <li class=\"item\"><a href=\"[field:arcurl/]\" title=\"[field:title/]\">\r\n              <div class=\"img\"><img src=\"[field:litpic/]\" alt=\"[field:title/]\"/></div>\r\n              <div class=\"txt\">\r\n                <h3 class=\"tit\">[field:title/]</h3>\r\n              </div>\r\n              </a></li>\r\n           ",450,826);
$z[1][4]=array();
$z[1][4]['row']="6";
$z[1][4]['titlelen']="60";
$z[1][4]['orderby']="pubdate";
$z[2]=Array("field","",998,1026);
$z[2][4]=array();
$z[2][4]['name']="typeurl";

?>