
          <li><a href="[field:typelink/]" title="[field:typename/]"><img src="/skin/images/fw[field:global name=autoindex runphp="yes"]@me=@me+1;[/field:global].jpg" alt="[field:typename/]">
            <div class="hui">
              <p>[field:typename/]<span>[field:description/]</span></p>
              <i class="icon"></i></div>
            <div class="dl"><i class="icon"></i>
              <p>[field:typename/]</p>
              <span>[field:description/]</span></div>
            </a></li>
          