<?php
$z[0]=Array("field","",203,231);
$z[0][4]=array();
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",240,269);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("field","",271,300);
$z[2][4]=array();
$z[2][4]['name']="typename";
$z[3]=Array("channel","\r\n          <li>\r\n            <div class=\"header\"><a href=\"[field:typelink/]\" title=\"[field:typename/]\">[field:typename/]</a></div>\r\n          </li>\r\n          ",382,595);
$z[3][4]=array();
$z[3][4]['type']="son";
$z[3][4]['noself']="yes";
$z[4]=Array("global","",900,923);
$z[4][4]=array();
$z[4][4]['name']="cfg_gsmc";
$z[5]=Array("global","",955,979);
$z[5][4]=array();
$z[5][4]['name']="cfg_email";
$z[6]=Array("global","",1006,1030);
$z[6][4]=array();
$z[6][4]['name']="cfg_phone";
$z[7]=Array("global","",1057,1079);
$z[7][4]=array();
$z[7][4]['name']="cfg_tel";
$z[8]=Array("global","",1106,1128);
$z[8][4]=array();
$z[8][4]['name']="cfg_add";
$z[9]=Array("arclist","\r\n		<li><a href=\"[field:arcurl/]\" title=\"[field:title/]\">\r\n          <div class=\"pic\"><img src=\"[field:litpic/]\" alt=\"[field:title/]\"></div>\r\n          <p >[field:title/]</p>\r\n          </a></li>\r\n		  ",1285,1565);
$z[9][4]=array();
$z[9][4]['typeid']="";
$z[9][4]['row']="9";
$z[9][4]['titlelen']="50";
$z[9][4]['orderby']="pubdate";

?>