<?php
$z[0]=Array("field","",190,219);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("field","",448,477);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("sql"," \r\n        [field:content  function='cn_substr(html2text(@me),500)'/]\r\n        ",501,651);
$z[2][4]=array();
$z[2][4]['sql']="Select content from dede_arctype where id=1";
$z[3]=Array("field","",712,735);
$z[3][4]=array();
$z[3][4]['name']="id";

?>