<div class="news_bg">
	<div class="container">
		<div class="row">
			<div class="col-xs-12 col-sm-12 col-md-12">
				<div class="product_head" data-move-y="-40px">
					<h2>{dede:field name='typename'/}</h2>
					<p>{dede:field name='description'/}</p>
				</div>
				<ul class="news_index" data-move-y="200px">
					<div class="col-sm-6 col-md-6 news_col">
						<li><a href="/a/xwzx/cjwt/18.html" title="劳务派遣市场如何实现共赢">劳务派遣市场如何实现共赢</a><span class='news_time2'><strong>10</strong><i>2018-10</i></span><br>
						<em class='news_time2'> 随着我国市场经济的日益成熟，劳务派遣作为一种新的用工方式，逐渐发展起来。纵观我国劳...</em></li>
					</div>
<div class="col-sm-6 col-md-6 news_col">
						<li><a href="/a/xwzx/cjwt/17.html" title="劳务派遣用工的成本优势">劳务派遣用工的成本优势</a><span class='news_time2'><strong>20</strong><i>2018-09</i></span><br>
						<em class='news_time2'> 1、招募与甄选方面。 企业如果想要雇佣到合适的劳动力，必须要付出一定的招募与甄选成本。...</em></li>
					</div>
<div class="col-sm-6 col-md-6 news_col">
						<li><a href="/a/xwzx/cjwt/16.html" title="自我派遣的规定与处罚">自我派遣的规定与处罚</a><span class='news_time2'><strong>19</strong><i>2018-09</i></span><br>
						<em class='news_time2'> 一、用人单位是否能够进行自我派遣? 根据《劳动合同法》第67条规定，用人单位不得设立劳务...</em></li>
					</div>
<div class="col-sm-6 col-md-6 news_col">
						<li><a href="/a/xwzx/cjwt/15.html" title="劳务派遣存在哪些问题">劳务派遣存在哪些问题</a><span class='news_time2'><strong>18</strong><i>2018-09</i></span><br>
						<em class='news_time2'> 一、工资支付不透明。 由于 劳务派遣 工的劳动关系和工作岗位分属两家，出现部分劳务型企...</em></li>
					</div>
<div class="col-sm-6 col-md-6 news_col">
						<li><a href="/a/xwzx/cjwt/14.html" title="劳务派遣为员工提供哪些你不知的便利">劳务派遣为员工提供哪些你不知的便利</a><span class='news_time2'><strong>17</strong><i>2018-09</i></span><br>
						<em class='news_time2'> 一、更有利于保护个人的合法权益。 劳务人员被派遣用工单位,招才通劳务公司就充当了监督者...</em></li>
					</div>
<div class="col-sm-6 col-md-6 news_col">
						<li><a href="/a/xwzx/cjwt/13.html" title="为什么不废除劳务派遣?">为什么不废除劳务派遣?</a><span class='news_time2'><strong>15</strong><i>2018-09</i></span><br>
						<em class='news_time2'> 认识什么是 劳务派遣 。 劳动派遣是一种指用工企业可以根据自身工作和发展需要，通过我公...</em></li>
					</div>

				</ul>
			</div>
		</div>
	</div>
</div>