<div class="col-lg-4 col-sm-6">
            <div class="item">
             <dl class="reset">
              <div class="imgBox">
               <a href="[field:arcurl/]" title="[field:title/]"><img class="lazyImg" src="[field:litpic/]" data-original="[field:litpic/]" alt="[field:title/]" style="display: inline;"></a>
              </div>
              <dt>[field:title/]</dt>
              <dd><a href="[field:arcurl/]">查看详情</a></dd>
             </dl>
            </div>
           </div>