<?php
$z[0]=Array("field","",82,111);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("field","",335,358);
$z[1][4]=array();
$z[1][4]['name']="id";
$z[2]=Array("channel","\r\n          <li><a href=\"list.php?tid=[field:id/]\" title=\"[field:typename/]\">[field:typename/]</a></li>\r\n          ",387,555);
$z[2][4]=array();
$z[2][4]['type']="son";
$z[2][4]['noself']="yes";
$z[3]=Array("field","",2393,2416);
$z[3][4]=array();
$z[3][4]['name']="id";

?>