<li class="item"><a href="[field:arcurl/]" title="[field:title/]"><img src="[field:litpic/]" alt="[field:title/]"/>
                  <div class="tit">
                    <p class="p1">[field:title/]</p>
                    <p class="p2"><span class="s2">[field:pubdate function="MyDate('d',@me)"/]</span><span class="s1">[field:pubdate function="MyDate('Y-m',@me)"/]</span></p>
                  </div>
                  </a></li>