<li class="item"><a class="clearfix" href="[field:arcurl/]" title="[field:title/]">
            <div class="txt fr">
              <h3>[field:title/]</h3>
              <div class="mark"><span>时间：[field:pubdate function="MyDate('Y-m-d',@me)"/]</span><span>浏览量：[field:click/]</span></div>
              <p class="desc">[field:description function="cn_substr(@me,200)"/]...</p>
            </div>
            <div class="img"><img src="[field:litpic/]" alt="[field:title/]"></div>
            </a></li>