<?php
$z[0]=Array("field","",52,81);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("field","",88,119);
$z[1][4]=array();
$z[1][4]['name']="typenameen";
$z[2]=Array("field","",213,241);
$z[2][4]=array();
$z[2][4]['name']="typeurl";
$z[3]=Array("channel","\r\n				<li class=\"layer1\"><a href='[field:typelink/]'>[field:typename/]</a></li>\r\n				",264,402);
$z[3][4]=array();
$z[3][4]['type']="son";
$z[3][4]['noself']="yes";

?>