<div class="container">
	<div class="row">
		<div class="col-xs-12 col-sm-12 col-md-12">
			<div class="news_head" data-move-y="-40px">
				<h2>{dede:field name='typename'/}</h2>
				<span></span>
				<p>{dede:field name='description'/}</p>
			</div>
			<div class="col-xs-12 col-sm-12 col-md-12">
				<div class="col-sm-12 col-md-5 news_img" data-move-x="-100px" style="background-image: url(/skin/images/news.jpg);">
				</div>
				<div class="col-xs-12 col-sm-12 col-md-7 news_text" data-move-y="150px">
					<ul class="news_index">
						<li>
						<span>
						<strong>10</strong>
						<i>2018-10</i>
						</span>
						<a href="news/html/?431.html" title="劳务派遣市场如何实现共赢">劳务派遣市场如何实现共赢</a><br>
						<em>随着我国市场经济的日益成熟，劳务派遣作为一种新的用工方式，逐渐发展起来。纵观我国劳...</em>
						</li>
<li>
						<span>
						<strong>20</strong>
						<i>2018-09</i>
						</span>
						<a href="news/html/?431.html" title="劳务派遣用工的成本优势">劳务派遣用工的成本优势</a><br>
						<em>1、招募与甄选方面。 企业如果想要雇佣到合适的劳动力，必须要付出一定的招募与甄选成本。...</em>
						</li>
<li>
						<span>
						<strong>19</strong>
						<i>2018-09</i>
						</span>
						<a href="news/html/?431.html" title="自我派遣的规定与处罚">自我派遣的规定与处罚</a><br>
						<em>一、用人单位是否能够进行自我派遣? 根据《劳动合同法》第67条规定，用人单位不得设立劳务...</em>
						</li>
<li>
						<span>
						<strong>18</strong>
						<i>2018-09</i>
						</span>
						<a href="news/html/?431.html" title="劳务派遣存在哪些问题">劳务派遣存在哪些问题</a><br>
						<em>一、工资支付不透明。 由于 劳务派遣 工的劳动关系和工作岗位分属两家，出现部分劳务型企...</em>
						</li>

					</ul>
				</div>
			</div>
		</div>
	</div>
</div>