<?php
$z[0]=Array("field","",93,122);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("arclist","\r\n        <li class=\"item\"><a href=\"view.php?aid=[field:id/]\" title=\"[field:title/]\">\r\n          <figure class=\"img\"><img src=\"[field:litpic/]\" alt=\"[field:title/]\"></figure>\r\n          <h3 class=\"tit\">[field:title/]</h3>\r\n          </a></li>\r\n       ",250,570);
$z[1][4]=array();
$z[1][4]['row']="4";
$z[1][4]['titlelen']="60";
$z[1][4]['orderby']="pubdate";
$z[2]=Array("field","",643,666);
$z[2][4]=array();
$z[2][4]['name']="id";

?>