<?php
$z[0]=Array("arcurl","",13,28);
$z[0][4]=array();
$z[1]=Array("title","",37,51);
$z[1][4]=array();
$z[2]=Array("pubdate","",89,132);
$z[2][4]=array();
$z[2][4]['function']="MyDate('d',@me)";
$z[3]=Array("pubdate","",136,181);
$z[3][4]=array();
$z[3][4]['function']="MyDate('Y-m',@me)";
$z[4]=Array("title","",204,218);
$z[4][4]=array();
$z[5]=Array("description","",238,288);
$z[5][4]=array();
$z[5][4]['function']="cn_substr(@me,150)";

?>