<?php
$z[0]=Array("field","",196,225);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("field","",265,297);
$z[1][4]=array();
$z[1][4]['name']="description";
$z[2]=Array("arclist","<li><a href=\"[field:arcurl/]\" title=\"[field:title/]\"><em><span>[field:pubdate function=\"MyDate('d',@me)\"/]</span>[field:pubdate function=\"MyDate('Y-m',@me)\"/]</em>\r\n                <h3>\r\n                  <p>[field:title/]<span>[field:description function=\"cn_substr(@me,120)\"/]...</span></p>\r\n                </h3>\r\n                </a></li>\r\n				",577,995);
$z[2][4]=array();
$z[2][4]['row']="10";
$z[2][4]['titlelen']="50";
$z[2][4]['orderby']="pubdate";
$z[3]=Array("field","",1225,1253);
$z[3][4]=array();
$z[3][4]['name']="typeurl";

?>