








































<field:email itemname="您的邮箱" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:email>

<field:content itemname="给我们留言" autofield="1" type="multitext" isnull="true" default=""  maxlength="250" page="">
</field:content>

<field:liuyantime itemname="留言时间" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:liuyantime>
