<?php
$z[0]=Array("field","",49,77);
$z[0][4]=array();
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",86,115);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("field","",117,146);
$z[2][4]=array();
$z[2][4]['name']="typename";
$z[3]=Array("channel","  <a href=\"[field:typelink/]\" title=\"[field:typename/]\">[field:typename/]</a>",175,305);
$z[3][4]=array();
$z[3][4]['type']="son";
$z[3][4]['noself']="yes";

?>