<td  class="">
<a class="{dede:field.currentstyle/}" href="{dede:field name='typeurl'/}" title="{dede:field name='typename'/}">{dede:field name='typename'/}<br /><!-- <span></span> --><div></div></a>
                        <div class="nav_tan">
						
                {dede:channel type='son' noself='yes' }
<li><a href='[field:typelink/]'>[field:typename/]</a></li>
{/dede:channel}
				
				
				          </div>  
				</td>