<?php
$z[0]=Array("field","",26,52);
$z[0][4]=array();
$z[0][4]['name']="currentstyle";
$z[1]=Array("field","",60,88);
$z[1][4]=array();
$z[1][4]['name']="typeurl";
$z[2]=Array("field","",97,126);
$z[2][4]=array();
$z[2][4]['name']="typename";
$z[3]=Array("field","",128,157);
$z[3][4]=array();
$z[3][4]['name']="typename";
$z[4]=Array("channel","\r\n<li><a href='[field:typelink/]'>[field:typename/]</a></li>\r\n",273,389);
$z[4][4]=array();
$z[4][4]['type']="son";
$z[4][4]['noself']="yes";

?>