<?php
$z[0]=Array("field","",179,208);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("arclist","\r\n              <li><a href=\"[field:arcurl/]\" title=\"[field:title/]\"><img class=\"img\" src=\"[field:litpic/]\" alt=\"[field:title/]\"/>\r\n                <div class=\"txt\">\r\n                  <h3>[field:title/]</h3>\r\n                  <p>[field:description function=\"cn_substr(@me,155)\"/]...</p>\r\n                </div>\r\n                </a></li>\r\n           ",487,917);
$z[1][4]=array();
$z[1][4]['row']="4";
$z[1][4]['titlelen']="50";
$z[1][4]['orderby']="pubdate";
$z[1][4]['flag']="h";
$z[2]=Array("arclist","\r\n            <li class=\"item\"><a href=\"[field:arcurl/]\" title=\"[field:title/]\">\r\n              <div class=\"time fl\"><b>29</b>2019-10</div>\r\n              <h3>[field:title/]</h3>\r\n              <p>[field:description /]...</p>\r\n              </a></li>\r\n            ",1213,1547);
$z[2][4]=array();
$z[2][4]['row']="3";
$z[2][4]['titlelen']="50";
$z[2][4]['orderby']="pubdate";
$z[3]=Array("field","",1613,1641);
$z[3][4]=array();
$z[3][4]['name']="typeurl";

?>