<?php
$z[0]=Array("field","",67,93);
$z[0][4]=array();
$z[0][4]['name']="currentstyle";
$z[1]=Array("field","",101,129);
$z[1][4]=array();
$z[1][4]['name']="typeurl";
$z[2]=Array("field","",138,167);
$z[2][4]=array();
$z[2][4]['name']="typename";
$z[3]=Array("field","",173,202);
$z[3][4]=array();
$z[3][4]['name']="typename";
$z[4]=Array("channel","\r\n		   <a class=\"subA\" href=\"[field:typelink/]\" title=\"[field:typename/]\">[field:typename/]</a> \r\n		  ",248,403);
$z[4][4]=array();
$z[4][4]['type']="son";
$z[4][4]['noself']="yes";

?>