<li class="item">
		<a class="hvr-underline-from-center1 " class="{dede:field.currentstyle/}" href="{dede:field name='typeurl'/}" title="{dede:field name='typename'/}">
		{dede:field name='typename'/}
		</a>
         <div class="suNav">  
		  {dede:channel type='son' noself='yes'}
		   <a class="subA" href="[field:typelink/]" title="[field:typename/]">[field:typename/]</a> 
		  {/dede:channel} 
		 </div>
        </li>