<?php
$z[0]=Array("field","",192,221);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("channel","\r\n            <li class='item[field:global runphp='yes' name=autoindex]\r\n                      \$a=\"\";\r\n                        \$b=\" hover\";\r\n                        if ((@me%0)==0 && @me!=0)  @me=\$a;\r\n                        else  @me=\$b;\r\n                        [/field:global]'><a href=\"[field:typelink/]\" title=\"[field:typename/]\">[field:typename/]</a></li>\r\n            ",502,930);
$z[1][4]=array();
$z[1][4]['type']="son";
$z[1][4]['noself']="yes";
$z[2]=Array("arclist","\r\n				<li class=\"item\"><a href=\"[field:arcurl/]\" title=\"[field:title/]\"><img src=\"[field:litpic/]\" alt=\"[field:title/]\"/>\r\n                  <div class=\"tit\">\r\n                    <p class=\"p1\">[field:title/]</p>\r\n                    <p class=\"p2\"><span class=\"s2\">[field:pubdate function=\"MyDate('d',@me)\"/]</span><span class=\"s1\">[field:pubdate function=\"MyDate('Y-m',@me)\"/]</span></p>\r\n                  </div>\r\n                  </a></li>\r\n				  {dede:arclist}\r\n              </ul>\r\n            </div>\r\n            <div class=\"hd\"> <span class=\"prev icon\"></span> <a href=\"{dede:field name='typeurl'",1227,1888);
$z[2][4]=array();
$z[2][4]['row']="10";
$z[2][4]['titlelen']="50";
$z[2][4]['orderby']="pubdate";

?>