<div class="case_bg">
	<div class="container">
		<div class="row">
			<div class="col-xs-12 col-sm-12 col-md-12">
				<div class="product_head" data-move-y="-40px">
					<h2>{dede:field name='typename'/}</h2>
					<span></span>
					<p>{dede:field name='description'/}</p>
				</div>
				<div class="case_list">
					{dede:arclist typeid='' row='4' titlelen='50' orderby='pubdate'}
					<div class="col-sm-4 col-md-3 col-mm-6 case_img" data-move-y="50px">
						<a href="/a/qyxc/37.html"><img src="/uploads/allimg/190609/1-1Z60Z9515E29-lp.jpg" class="opacity_img" alt="客户案例5"/></a>
						<p class="case_title">
							<a href="/a/qyxc/37.html">客户案例5</a>
						</p>
					</div>
					{/dede:arclist}

				</div>
			</div>
		</div>
	</div>
</div>