<?php
$z[0]=Array("field","",112,143);
$z[0][4]=array();
$z[0][4]['name']="typenameen";
$z[1]=Array("field","",157,189);
$z[1][4]=array();
$z[1][4]['name']="description";
$z[2]=Array("arclist","\r\n					<li class=\"animated flipInX\" style=\"width:auto\"><a href=\"[field:arcurl/]\" title=\"[field:title/]\" target=\"_blank\"><img src=\"[field:litpic/]\" width=\"320\" height=\"240\" alt=\"[field:title/]\"/>\r\n					<p>[field:title/]</p>\r\n					</a></li>\r\n					",342,656);
$z[2][4]=array();
$z[2][4]['row']="3";
$z[2][4]['titlelen']="50";
$z[2][4]['orderby']="pubdate";

?>