<?php
$z[0]=Array("arcurl","",61,76);
$z[0][4]=array();
$z[1]=Array("title","",85,99);
$z[1][4]=array();
$z[2]=Array("title","",101,115);
$z[2][4]=array();
$z[3]=Array("pubdate","",152,195);
$z[3][4]=array();
$z[3][4]['function']="MyDate('d',@me)";
$z[4]=Array("pubdate","",207,252);
$z[4][4]=array();
$z[4][4]['function']="MyDate('Y-m',@me)";
$z[5]=Array("description","",299,349);
$z[5][4]=array();
$z[5][4]['function']="cn_substr(@me,120)";

?>