
<field:j-cname itemname="姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:j-cname>

<field:sex itemname="性别" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:sex>

<field:j-tel itemname="电话" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:j-tel>

<field:education itemname="学历" autofield="1" type="select" isnull="true" default="初中及以下,高中,中专,大专,本科,研究生及以上"  maxlength="250" page="">
</field:education>

<field:experience itemname="工作经历" autofield="1" type="multitext" isnull="true" default=""  maxlength="250" page="">
</field:experience>

<field:file itemname="上传简历" autofield="1" type="addon" isnull="true" default=""  maxlength="250" page="">
</field:file>



<field:ypgw itemname="应聘岗位" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:ypgw>

<field:liuyantime itemname="留言时间" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:liuyantime>
