<?php
$z[0]=Array("field","",128,151);
$z[0][4]=array();
$z[0][4]['name']="id";
$z[1]=Array("field","",196,225);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("field","",329,360);
$z[2][4]=array();
$z[2][4]['name']="typenameen";
$z[3]=Array("field","",438,467);
$z[3][4]=array();
$z[3][4]['name']="typename";
$z[4]=Array("field","",556,579);
$z[4][4]=array();
$z[4][4]['name']="id";
$z[5]=Array("sql"," \r\n            [field:content  function='cn_substr(html2text(@me),400)'/]...\r\n            ",609,770);
$z[5][4]=array();
$z[5][4]['sql']="Select content from dede_arctype where id=1";
$z[6]=Array("field","",832,855);
$z[6][4]=array();
$z[6][4]['name']="id";

?>