<li class='{dede:field.currentstyle/}'><a class="aLink" href="{dede:field name='typeurl'/}" title="{dede:field name='typename'/}">{dede:field name='typename'/}<i></i></a>
          <ul class="subnav">
            {dede:channel type='son' noself='yes'}
            <li class="nav1"><a href="[field:typelink/]" title="[field:typename/]">[field:typename/]</a></li>
            {/dede:channel}
          </ul>
        </li>