<?php
$z[0]=Array("field","",95,118);
$z[0][4]=array();
$z[0][4]['name']="id";
$z[1]=Array("field","",130,158);
$z[1][4]=array();
$z[1][4]['name']="typeimg";
$z[2]=Array("field","",165,194);
$z[2][4]=array();
$z[2][4]['name']="typename";
$z[3]=Array("field","",341,370);
$z[3][4]=array();
$z[3][4]['name']="typename";
$z[4]=Array("sql"," \r\n        [field:content  function='cn_substr(html2text(@me),500)'/]\r\n        ",460,610);
$z[4][4]=array();
$z[4][4]['sql']="Select content from dede_arctype where id=1";
$z[5]=Array("field","",671,694);
$z[5][4]=array();
$z[5][4]['name']="id";

?>