<div id="floor_4_main">
    <div class="floor_4 w1200">
      <div class="in_title clearfix" aos="fade-up" aos-easing="ease" aos-duration="700">
        <p class="entit" aos="fade-up" aos-easing="ease" aos-duration="700">{dede:field name='typenameen'/}</p>
        <h3 class="tit clearfix" aos="fade-up" aos-easing="ease" aos-duration="700" aos-delay="100"><em class="line"></em><span class="word">{dede:field name='typename'/}</span><em class="line"></em></h3>
      </div>
      <div class="proCase" id="scroll" aos="fade-up" aos-easing="ease" aos-duration="700" aos-delay="200">
        <div class="bd">
          <ul class="list clearfix">
            {dede:arclist row='10' titlelen='50' orderby='pubdate'}
			<li><a href="[field:arcurl/]" title="[field:title/]"><img class="img" src="/uploads/allimg/190108/1-1Z10Q643580-L.jpg" alt="[field:title/]"/>
              <div class="title">
                <h3 class="tit">[field:title/]</h3>
              </div>
              </a></li>
			  {/dede:arclist}
          </ul>
        </div>
        <div class="hd"><span class="prev ico"></span><span class="next ico"></span></div>
      </div>
    </div>
  </div>