<?php
$z[0]=Array("field","",224,255);
$z[0][4]=array();
$z[0][4]['name']="typenameen";
$z[1]=Array("field","",402,431);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("arclist","\r\n			<li><a href=\"[field:arcurl/]\" title=\"[field:title/]\"><img class=\"img\" src=\"/uploads/allimg/190108/1-1Z10Q643580-L.jpg\" alt=\"[field:title/]\"/>\r\n              <div class=\"title\">\r\n                <h3 class=\"tit\">[field:title/]</h3>\r\n              </div>\r\n              </a></li>\r\n			  ",665,1023);
$z[2][4]=array();
$z[2][4]['row']="10";
$z[2][4]['titlelen']="50";
$z[2][4]['orderby']="pubdate";

?>