<?php
$z[0]=Array("field","",103,132);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("field","",149,180);
$z[1][4]=array();
$z[1][4]['name']="typenameen";
$z[2]=Array("field","",223,255);
$z[2][4]=array();
$z[2][4]['name']="description";
$z[3]=Array("type","<li role=\"presentation\" class=\"active\"><a href=\"#home\" aria-controls=\"home\" role=\"tab\" data-toggle=\"tab\">[field:typename /]</a></li>",384,551);
$z[3][4]=array();
$z[3][4]['typeid']="13";
$z[4]=Array("type","<li role=\"presentation\"><a href=\"#profile\" aria-controls=\"profile\" role=\"tab\" data-toggle=\"tab\">[field:typename /]</a></li>",557,715);
$z[4][4]=array();
$z[4][4]['typeid']="14";
$z[5]=Array("field","",754,782);
$z[5][4]=array();
$z[5][4]['name']="typeurl";

?>