<div class="news mt">
	<div class="container">
		<div class="row">
			<div class="newtit">
				<h2>{dede:field name='typename'/}</h2>
				<span>{dede:field name='typenameen'/}</span>
			</div>
			<p class="newstext">{dede:field name='description'/}</p>
			  <!-- Nav tabs -->
			  <ul class="nav nav-tabs col-lg-offset-4 col-md-offset-4 col-xs-offset-1" role="tablist">
				{dede:type typeid='13'}<li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">[field:typename /]</a></li>{/dede:type}
				{dede:type typeid='14'}<li role="presentation"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">[field:typename /]</a></li>{/dede:type}
				<li role="presentation"><a href="{dede:field name='typeurl'/}">查看更多</a></li>
			  </ul>
			  <!-- Tab panes -->
			  <div class="tab-content">
				<div role="tabpanel" class="tab-pane active" id="home">
					<div class="container">
						<div class="row">
							<div class="col-lg-4 col-lg-offset-2 hidden-xs hidden-md img"><img src="/skin/images/adv.png"/></div>
							<div class="col-lg-4 col-xs-12">
								<ul class="newslist">
									<li><a href="/xwzx/gsxw/30.html"><i>劳务派遣市场如何实现共赢</i><span>2018-10-10</span></a></li>
<li><a href="/xwzx/gsxw/36.html"><i>劳务协议与劳动合同的区别有哪些？</i><span>2018-07-31</span></a></li>
<li><a href="/xwzx/gsxw/35.html"><i>如何选择合适的人力资源外包公司？</i><span>2018-07-27</span></a></li>
<li><a href="/xwzx/gsxw/34.html"><i>为什么企业热衷于人力资源外包服务</i><span>2018-07-25</span></a></li>
<li><a href="/xwzx/gsxw/33.html"><i>知名企业HR看人才派遣业的发展</i><span>2018-07-23</span></a></li>
<li><a href="/xwzx/gsxw/32.html"><i>劳务派遣工资发放的方法及流程</i><span>2018-07-16</span></a></li>

								</ul>
							</div>
						</div>
					</div>
				</div>
				<div role="tabpanel" class="tab-pane" id="profile">
					<div class="container">
						<div class="row">
							<div class="col-lg-4 col-lg-offset-2 hidden-xs hidden-md img"><img src="/skin/images/adv.png"/></div>
							<div class="col-lg-4 col-xs-12 col-md-12">
								<ul class="newslist">
									<li><a href="/xwzx/xyzx/29.html"><i>劳务派遣用工的成本优势</i><span>2018-09-20</span></a></li>
<li><a href="/xwzx/xyzx/28.html"><i>自我派遣的规定与处罚</i><span>2018-09-19</span></a></li>
<li><a href="/xwzx/xyzx/27.html"><i>劳务派遣存在哪些问题</i><span>2018-09-18</span></a></li>
<li><a href="/xwzx/xyzx/26.html"><i>劳务派遣为员工提供哪些你不知的便利?</i><span>2018-09-17</span></a></li>
<li><a href="/xwzx/xyzx/25.html"><i>为什么不废除劳务派遣?</i><span>2018-09-15</span></a></li>
<li><a href="/xwzx/xyzx/24.html"><i>劳务派遣退回流程</i><span>2018-09-14</span></a></li>

								</ul>
							</div>
						</div>
					</div>
				</div>
			  </div>
			
		</div>
	</div>
</div>