<dl class="clearfix">
                <dt><a href="[field:arcurl/]"><img src="[field:litpic/]" alt="[field:title/]"></a></dt>
                <dd>
                    <div class="title">
                        <a href="[field:arcurl/]">
                            <p>[field:title/]</p>
                            <em>[[field:pubdate function="MyDate('Y-m-d',@me)"/]]</em>
                        </a>
                    </div>
                    <div class="des">[field:description function="cn_substr(@me,300)"/]...</div>
                    <a href="[field:arcurl/]" class="more1">+ 查看详情</a>
                </dd>
            </dl>