<?php
$z[0]=Array("field","",102,131);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("field","",144,176);
$z[1][4]=array();
$z[1][4]['name']="description";
$z[2]=Array("channel","\r\n						<li><a class=\"biglink\" href='[field:typelink/]'>[field:typename/]</a></li>\r\n						",367,511);
$z[2][4]=array();
$z[2][4]['typeid']="5";
$z[2][4]['noself']="yes";
$z[3]=Array("global","",562,584);
$z[3][4]=array();
$z[3][4]['name']="cfg_tel";
$z[4]=Array("arclist","\r\n				<div class=\"col-sm-4 col-md-4 col-mm-6 case_img\" data-move-y=\"50px\">\r\n					<a href=\"[field:arcurl/]\"><img src=\"[field:litpic/]\" class=\"opacity_img\" alt=\"[field:title/]\"/></a>\r\n					<p class=\"case_title\">\r\n						<a href=\"[field:arcurl/]\">[field:title/]</a>\r\n					</p>\r\n				</div>\r\n				",705,1074);
$z[4][4]=array();
$z[4][4]['typeid']="";
$z[4][4]['row']="6";
$z[4][4]['titlelen']="50";
$z[4][4]['orderby']="pubdate";

?>