












<field:email itemname="邮箱" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:email>

<field:address itemname="地址" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:address>

<field:content itemname="留言内容" autofield="1" type="multitext" isnull="true" default=""  maxlength="250" page="">
</field:content>

<field:liuyantime itemname="留言时间" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:liuyantime>
