<li>
                    	<a href="[field:arcurl/]">
                    	<div class="newslist-l">
                       		<h2>[field:pubdate function="MyDate('d',@me)"/]</h2>
                            <p>[field:pubdate function="MyDate('Y-m',@me)"/]</p>
                        </div>
                        <div class="newslist-r">
                       		<h2>[field:title/]</h2>
                            <p>[field:description/]</p>
                        </div>
                        </a>
                    </li>