<dl class="in_dl1">
                <dt><a href="{dede:field name=typeurl/}" title="{dede:field name=typename/}" class="img"><img src="{dede:field name=typeimg/}" alt="{dede:field name=typename/}"></a></dt>
                <dd><a href="{dede:field name=typeurl/}" title="{dede:field name=typename/}">{dede:field name=typename/}</a></dd>
                <dd>八大核心优势：1、圆滑美观；2、无接缝 更高端；3、结实更牢固；4、环保更耐用；5、安装更便捷；6、层板不松动；7、5A级防护。<BR>
          <BR>
          产品优势大揭秘：1、食品级材质； 2、轻奢艺术美；3、耐高温；4、不怕潮；5、抑菌；6、防虫；7、不变形； 8、抗污染；9、一体化。
</dd>
			</dl>