<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]=array();
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/190109/1-1Z10ZU324.jpg ",93,234);
$z[1][4]=array();
$z[1][4]['ddimg']="/uploads/allimg/190109/1-1Z10ZU324.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="585";
$z[1][4]['height']="439";
$z[2]=Array("img"," /uploads/allimg/190109/1-1Z10ZU326.jpg ",236,377);
$z[2][4]=array();
$z[2][4]['ddimg']="/uploads/allimg/190109/1-1Z10ZU326.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="585";
$z[2][4]['height']="439";
$z[3]=Array("img"," /uploads/allimg/190109/1-1Z10ZU327.jpg ",379,520);
$z[3][4]=array();
$z[3][4]['ddimg']="/uploads/allimg/190109/1-1Z10ZU327.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="585";
$z[3][4]['height']="439";

?>