<?php
$z[0]=Array("field","",150,179);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("field","",217,249);
$z[1][4]=array();
$z[1][4]['name']="description";
$z[2]=Array("channel","\r\n          <li><a href=\"[field:typelink/]\" title=\"[field:typename/]\"><img src=\"/skin/images/fw[field:global name=autoindex runphp=\"yes\"]@me=@me+1;[/field:global].jpg\" alt=\"[field:typename/]\">\r\n            <div class=\"hui\">\r\n              <p>[field:typename/]<span>[field:description/]</span></p>\r\n              <i class=\"icon\"></i></div>\r\n            <div class=\"dl\"><i class=\"icon\"></i>\r\n              <p>[field:typename/]</p>\r\n              <span>[field:description/]</span></div>\r\n            </a></li>\r\n          ",411,985);
$z[2][4]=array();
$z[2][4]['type']="son";
$z[2][4]['currentstyle']="";

?>