<?php
$z[0]=Array("field","",124,153);
$z[0][4]=array();
$z[0][4]['name']="typenameen";
$z[1]=Array("field","",166,192);
$z[1][4]=array();
$z[1][4]['name']="typeurl";
$z[2]=Array("field","",201,228);
$z[2][4]=array();
$z[2][4]['name']="typename";
$z[3]=Array("field","",230,257);
$z[3][4]=array();
$z[3][4]['name']="typename";
$z[4]=Array("arclist","\r\n            <div class=\"item\">\r\n                <dd class=\"not-animated\"><a href=\"[field:arcurl/]\" title=\"[field:fulltitle/]\">\r\n                    <div class=\"imgs\"><img src=\"[field:litpic/]\" alt=\"[field:fulltitle/]\"></div>\r\n                    <h3>[field:title/]\r\n                        <p>[field:description/]...</p>\r\n                    </h3>\r\n                    </a></dd>\r\n            </div>\r\n			",338,792);
$z[4][4]=array();
$z[4][4]['row']="10";
$z[4][4]['titlelen']="100";

?>