<?php
$z[0]=Array("field","",45,73);
$z[0][4]=array();
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",82,111);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("field","",113,142);
$z[2][4]=array();
$z[2][4]['name']="typename";
$z[3]=Array("channel","<a href=\"[field:typelink/]\" title=\"[field:typename/]\">[field:typename/]</a>  ",169,299);
$z[3][4]=array();
$z[3][4]['type']="son";
$z[3][4]['noself']="yes";

?>