{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='2'/}
{dede:img ddimg='/uploads/allimg/200207/1-20020H12229.jpg' text='' width='440' height='330'} /uploads/allimg/200207/1-20020H12229.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/200207/1-20020H12239.jpg' text='' width='440' height='330'} /uploads/allimg/200207/1-20020H12239.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/200207/1-20020H12243.jpg' text='' width='440' height='330'} /uploads/allimg/200207/1-20020H12243.jpg {/dede:img}
