<?php
$z[0]=Array("field","",144,173);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("field","",197,229);
$z[1][4]=array();
$z[1][4]['name']="description";
$z[2]=Array("arclist","\r\n		<li><a href=\"[field:arcurl/]\"  title=\"[field:title/]\"><span>[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</span>[field:title/]</a></li>\r\n		",295,519);
$z[2][4]=array();
$z[2][4]['typeid']="";
$z[2][4]['row']="5";
$z[2][4]['titlelen']="60";
$z[2][4]['orderby']="pubdate";

?>