<?php
$z[0]=Array("global","\r\n                      \$a=\"style='margin-right:0;'\";\r\n                        \$b=\"\";\r\n                        if ((@me%3)==0 && @me!=15)  @me=\$a;\r\n                        else  @me=\$b;\r\n                        ",17,285);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[0][4]['name']="autoindex";
$z[1]=Array("arcurl","",295,310);
$z[1][4]=array();
$z[2]=Array("title","",319,333);
$z[2][4]=array();
$z[3]=Array("litpic","",345,360);
$z[3][4]=array();
$z[4]=Array("title","",367,381);
$z[4][4]=array();
$z[5]=Array("title","",401,415);
$z[5][4]=array();

?>