<li class="item" [field:global runphp='yes' name=autoindex]
                      $a="style='margin-right:0;'";
                        $b="";
                        if ((@me%3)==0 && @me!=15)  @me=$a;
                        else  @me=$b;
                        [/field:global]><a href="[field:arcurl/]" title="[field:title/]"><img src="[field:litpic/]" alt="[field:title/]">
            <h3>[field:title/]</h3>
            </a></li>