<div class="in_news_list">
                <h4><a href="[field:arcurl/]" title="[field:fulltitle/]" class="img"><img src="[field:litpic/]" alt="[field:fulltitle/]"></a></h4>
                <h5><a href="[field:arcurl/]" title="[field:fulltitle/]">[field:title/]</a><span>[field:pubdate function="MyDate('Y-m-d',@me)"/]</span>
                    <p>[field:description/]...</p>
                </h5>
            </div>