<?php
$z[0]=Array("field","",216,245);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("field","",396,425);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("sql"," \r\n        [field:content  function='cn_substr(html2text(@me),606)'/]\r\n        ",461,611);
$z[2][4]=array();
$z[2][4]['sql']="Select content from dede_arctype where id=1";
$z[3]=Array("field","",655,683);
$z[3][4]=array();
$z[3][4]['name']="typeurl";

?>