<?php
$z[0]=Array("field","",318,347);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("field","",382,414);
$z[1][4]=array();
$z[1][4]['name']="description";
$z[2]=Array("arclist","\r\n					<div class=\"col-sm-4 col-md-4 col-mm-6 product_img\" data-move-y=\"50px\">\r\n						<div class=\"page_img\" data-move-y=\"50px\">\r\n							<a href=\"[field:arcurl/]\">\r\n							<img src=\"[field:litpic/]\" class=\"opacity_img\" alt=\"[field:title/]\">\r\n							</a>\r\n							<p class=\"product_title\">\r\n								<a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a>\r\n							</p>\r\n						</div>\r\n					</div>\r\n					",466,955);
$z[2][4]=array();
$z[2][4]['typeid']="";
$z[2][4]['row']="6";
$z[2][4]['titlelen']="50";
$z[2][4]['orderby']="pubdate";

?>