<?php
$z[0]=Array("id","",44,55);
$z[0][4]=array();
$z[1]=Array("title","",64,78);
$z[1][4]=array();
$z[2]=Array("title","",104,118);
$z[2][4]=array();
$z[3]=Array("pubdate","",159,206);
$z[3][4]=array();
$z[3][4]['function']="MyDate('Y-m-d',@me)";
$z[4]=Array("click","",221,235);
$z[4][4]=array();
$z[5]=Array("description","",265,314);
$z[5][4]=array();
$z[5][4]['function']="cn_substr(@me,80)";

?>