<?php
$z[0]=Array("field","",208,236);
$z[0][4]=array();
$z[0][4]['name']="typeimg";
$z[1]=Array("field","",243,272);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("sql"," \r\n        [field:content  function='cn_substr(html2text(@me),570)'/]\r\n        ",406,557);
$z[2][4]=array();
$z[2][4]['sql']="Select content from dede_arctype where id=16";
$z[3]=Array("field","",662,690);
$z[3][4]=array();
$z[3][4]['name']="typeurl";

?>