<?php
$z[0]=Array("field","",52,81);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("field","",88,119);
$z[1][4]=array();
$z[1][4]['name']="typenameen";
$z[2]=Array("channel","<li>[field:typename/]</li>",203,282);
$z[2][4]=array();
$z[2][4]['type']="son";
$z[2][4]['noself']="yes";
$z[3]=Array("arclist","\r\n				<div class=\"a4_t\">\r\n					<a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a>\r\n				</div>\r\n				<div class=\"a4_d\">\r\n					<dd>[field:description function=\"cn_substr(@me,300)\"/]...</dd>\r\n				</div>\r\n				",383,685);
$z[3][4]=array();
$z[3][4]['row']="2";
$z[3][4]['typeid']="13";
$z[3][4]['titlelen']="60";
$z[3][4]['orderby']="pubdate";

?>