<div class="a4 w1204">
	<div class="a_t">
		<span>{dede:field name='typename'/}</span>{dede:field name='typenameen'/}
	</div>
	<div class="c2a1">
		<div class="tabli1">
			<ul class="c2a_ul">
				{dede:channel type='son' noself='yes'}<li>[field:typename/]</li>{/dede:channel}
			</ul>
		</div>
	</div>
	<div class="c2b1">
		<div class="tab1">
			<div class="a4_1">
				{dede:arclist row='2' typeid='13' titlelen='60' orderby='pubdate'}
				<div class="a4_t">
					<a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a>
				</div>
				<div class="a4_d">
					<dd>[field:description function="cn_substr(@me,300)"/]...</dd>
				</div>
				{/dede:arclist}

			</div>
			<ul class="a4_ul2">
				<li><a href="/xwzx/gsgg/8.html" title="劳务派遣合同法律特点">劳务派遣合同法律特点</a><span>2018-08-18</span></li>
<li><a href="/xwzx/gsgg/7.html" title="劳务外包的意义与好处">劳务外包的意义与好处</a><span>2018-08-17</span></li>
<li><a href="/xwzx/gsgg/6.html" title="临时工外包对于企业的优势?">临时工外包对于企业的优势?</a><span>2018-08-08</span></li>
<li><a href="/xwzx/gsgg/5.html" title="企业使用业务外包的原因有哪些？">企业使用业务外包的原因有哪些？</a><span>2018-08-06</span></li>
<li><a href="/xwzx/gsgg/4.html" title="劳动争议、劳务纠纷怎么解决？">劳动争议、劳务纠纷怎么解决？</a><span>2018-08-03</span></li>
<li><a href="/xwzx/gsgg/3.html" title="劳务派遣基本含义">劳务派遣基本含义</a><span>2018-08-02</span></li>
<li><a href="/xwzx/gsgg/1.html" title="劳务派遣工比例有什么规定">劳务派遣工比例有什么规定</a><span>2018-08-01</span></li>


			</ul>
		</div><div class="tab1">
			<div class="a4_1">
				<div class="a4_t">
					<a href="/xwzx/qyxw/20.html" title="劳务派遣市场如何实现共赢">劳务派遣市场如何实现共赢</a>
				</div>
				<div class="a4_d">
					<dd>1、立法规范不全面，劳务纠纷处理惹争议。 《劳动合同法》虽然明确了劳务派遣岗位的范围：临时性、辅助性或者替代性。...</dd>
				</div>
<div class="a4_t">
					<a href="/xwzx/qyxw/19.html" title="逆向派遣无效单位需要担责">逆向派遣无效单位需要担责</a>
				</div>
				<div class="a4_d">
					<dd>一、什么是逆向派遣? 逆向派遣，也叫逆向劳务派遣，即与本单位部分或者大部分职工解除劳动合同后，让这些解除劳动合同...</dd>
				</div>

			</div>
			<ul class="a4_ul2">
				<li><a href="/xwzx/qyxw/18.html" title="劳务派遣找工作要交钱吗?">劳务派遣找工作要交钱吗?</a><span>2018-09-06</span></li>
<li><a href="/xwzx/qyxw/17.html" title="劳务派遣属于什么用工性质?">劳务派遣属于什么用工性质?</a><span>2018-09-05</span></li>
<li><a href="/xwzx/qyxw/16.html" title="劳务派遣有五险一金吗？">劳务派遣有五险一金吗？</a><span>2018-09-03</span></li>
<li><a href="/xwzx/qyxw/15.html" title="劳务派遣合同范本">劳务派遣合同范本</a><span>2018-09-01</span></li>
<li><a href="/xwzx/qyxw/14.html" title="劳务外包的定义是什么?">劳务外包的定义是什么?</a><span>2018-08-29</span></li>
<li><a href="/xwzx/qyxw/13.html" title="劳务派遣有什么优势？">劳务派遣有什么优势？</a><span>2018-08-28</span></li>
<li><a href="/xwzx/qyxw/12.html" title="劳务派遣需要什么资质？">劳务派遣需要什么资质？</a><span>2018-08-27</span></li>

			</ul>
		</div><div class="tab1">
			<div class="a4_1">
				<div class="a4_t">
					<a href="/xwzx/xydt/30.html" title="劳务派遣市场如何实现共赢">劳务派遣市场如何实现共赢</a>
				</div>
				<div class="a4_d">
					<dd>随着我国市场经济的日益成熟，劳务派遣作为一种新的用工方式，逐渐发展起来。纵观我国劳务行业的发展，虽历经坎坷，但...</dd>
				</div>
<div class="a4_t">
					<a href="/xwzx/xydt/29.html" title="劳务派遣用工的成本优势">劳务派遣用工的成本优势</a>
				</div>
				<div class="a4_d">
					<dd>1、招募与甄选方面。 企业如果想要雇佣到合适的劳动力，必须要付出一定的招募与甄选成本。这些成本既包括发布招募信息...</dd>
				</div>

			</div>
			<ul class="a4_ul2">
				<li><a href="/xwzx/xydt/28.html" title="自我派遣的规定与处罚">自我派遣的规定与处罚</a><span>2018-09-19</span></li>
<li><a href="/xwzx/xydt/27.html" title="劳务派遣存在哪些问题">劳务派遣存在哪些问题</a><span>2018-09-18</span></li>
<li><a href="/xwzx/xydt/26.html" title="劳务派遣为员工提供哪些你不知的便利?">劳务派遣为员工提供哪些你不知的便利?</a><span>2018-09-17</span></li>
<li><a href="/xwzx/xydt/25.html" title="为什么不废除劳务派遣?">为什么不废除劳务派遣?</a><span>2018-09-15</span></li>
<li><a href="/xwzx/xydt/24.html" title="劳务派遣退回流程">劳务派遣退回流程</a><span>2018-09-14</span></li>
<li><a href="/xwzx/xydt/23.html" title="劳务派遣运作过程中存在哪些问题?">劳务派遣运作过程中存在哪些问题?</a><span>2018-09-13</span></li>
<li><a href="/xwzx/xydt/22.html" title="劳务派遣风险预防">劳务派遣风险预防</a><span>2018-09-12</span></li>

			</ul>
		</div>
	</div>
	<script>$(".tabli1 li").eq(0).addClass("cur"),$(".tab1").eq(0).show(),$(".tabli1 li").hover(function(){$(this).addClass("cur").siblings().removeClass("cur");var s=$(this).index();$(".tab1").eq(s).show().siblings(".tab1").hide()})</script>
	<a href="/xwzx/" class="a4_more">了解一下</a>
</div>