<?php
$z[0]=Array("field","",224,255);
$z[0][4]=array();
$z[0][4]['name']="typenameen";
$z[1]=Array("field","",402,431);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("field","",664,693);
$z[2][4]=array();
$z[2][4]['name']="typename";
$z[3]=Array("sql"," \r\n        [field:content  function='cn_substr(html2text(@me),1000)'/]\r\n        ",763,914);
$z[3][4]=array();
$z[3][4]['sql']="Select content from dede_arctype where id=1";
$z[4]=Array("field","",968,996);
$z[4][4]=array();
$z[4][4]['name']="typeurl";
$z[5]=Array("global","",1098,1119);
$z[5][4]=array();
$z[5][4]['name']="cfg_qq";

?>