<?php
$z[0]=Array("field","",33,59);
$z[0][4]=array();
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",68,95);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("field","",148,174);
$z[2][4]=array();
$z[2][4]['name']="typeimg";
$z[3]=Array("field","",181,208);
$z[3][4]=array();
$z[3][4]['name']="typename";
$z[4]=Array("field","",272,299);
$z[4][4]=array();
$z[4][4]['name']="typename";

?>