<li class="clearfix" aos="fade-up" aos-easing="ease" aos-duration="700" aos-delay="100"><a href="[field:arcurl/]" title="[field:title/]"><span class="fl box1"><img src="[field:litpic/]" alt="[field:title/]"></span><span class="fl box2">
        <h1>[field:title/]</h1>
        <p>[field:description function="cn_substr(@me,200)"/]...</p>
        <span>阅读量：162</span></span><span class="right">
        <h3>10-29</h3>
        <p>2019</p>
        </span></a></li>