{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='2'/}
{dede:img ddimg='/uploads/allimg/200207/1-20020H12S3.jpg' text='' width='440' height='330'} /uploads/allimg/200207/1-20020H12S3.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/200207/1-20020H12S8.jpg' text='' width='440' height='330'} /uploads/allimg/200207/1-20020H12S8.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/200207/1-20020H12T3.jpg' text='' width='440' height='330'} /uploads/allimg/200207/1-20020H12T3.jpg {/dede:img}
