<div class="zjwy">
  <div class="content">
    <div class="zjwbBox">
      <h3 aos="fade-up" aos-easing="ease" aos-duration="700" aos-delay="100"> <a href="{dede:field name='typeurl'/}" title="{dede:field name='typename'/}">{dede:field name='typename'/}</a></h3>
      <div class="wy_tupian" aos="fade-up" aos-easing="ease" aos-duration="700" aos-delay="200"><img src="{dede:field name='typeimg'/}" alt="{dede:field name='typename'/}"/></div>
      <div class="wy_jianjie" aos="fade-up" aos-easing="ease" aos-duration="700" aos-delay="200">
        <dt>　　 {dede:sql sql='Select content from dede_arctype where id=1'} 
        [field:content  function='cn_substr(html2text(@me),1000)'/]
        {/dede:sql}...</dt>
        <dd><a href="/a/guanyuwomen/" title="查看更多">查看更多</a></dd>
      </div>
    </div>
  </div>
</div>