<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]=array();
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/191005/1-191005134930.jpg ",93,240);
$z[1][4]=array();
$z[1][4]['ddimg']="/uploads/allimg/191005/1-191005134930.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="720";
$z[1][4]['height']="540";
$z[2]=Array("img"," /uploads/allimg/191005/1-191005134930-50.jpg ",242,395);
$z[2][4]=array();
$z[2][4]['ddimg']="/uploads/allimg/191005/1-191005134930-50.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="720";
$z[2][4]['height']="540";
$z[3]=Array("img"," /uploads/allimg/191005/1-191005134930-51.jpg ",397,550);
$z[3][4]=array();
$z[3][4]['ddimg']="/uploads/allimg/191005/1-191005134930-51.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="720";
$z[3][4]['height']="540";
$z[4]=Array("img"," /uploads/allimg/191005/1-191005134931.jpg ",552,699);
$z[4][4]=array();
$z[4][4]['ddimg']="/uploads/allimg/191005/1-191005134931.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="720";
$z[4][4]['height']="540";

?>