<?php
$z[0]=Array("field","",105,134);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("field","",164,196);
$z[1][4]=array();
$z[1][4]['name']="description";
$z[2]=Array("channel","\r\n        <li><a href=\"list.php?tid=[field:id/]\" title=\"[field:typename/]\">[field:typename/]</a></li>\r\n        ",303,541);
$z[2][4]=array();
$z[2][4]['type']="son";
$z[2][4]['currentstyle']="<li><a href='list.php?tid=~id~'>~typename~</a></li>";
$z[3]=Array("arclist","\r\n        <li class=\"clearfix\"><a href=\"view.php?aid=[field:id/]\" title=\"[field:title/]\"><img src=\"[field:picname/]\" alt=\"[field:title/]\">\r\n          <p >[field:title/]</p>\r\n          </a></li>\r\n        ",648,920);
$z[3][4]=array();
$z[3][4]['row']="4";
$z[3][4]['titlelen']="50";
$z[3][4]['orderby']="pubdate";
$z[4]=Array("field","",983,1011);
$z[4][4]=array();
$z[4][4]['name']="typeurl";

?>