<?php
$z[0]=Array("field","",148,177);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("field","",210,242);
$z[1][4]=array();
$z[1][4]['name']="description";
$z[2]=Array("arclist","\r\n						<li>\r\n						<span>\r\n						<strong>[field:pubdate function=\"MyDate('d',@me)\"/]</strong>\r\n						<i>[field:pubdate function=\"MyDate('Y-m',@me)\"/]</i>\r\n						</span>\r\n						<a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a><br>\r\n						<em>[field:description function=\"cn_substr(@me,120)\"/]...</em>\r\n						</li>\r\n						",555,973);
$z[2][4]=array();
$z[2][4]['typeid']="";
$z[2][4]['row']="4";
$z[2][4]['titlelen']="60";
$z[2][4]['orderby']="pubdate";

?>