<?php
$z[0]=Array("arcurl","",89,104);
$z[0][4]=array();
$z[1]=Array("fulltitle","",114,132);
$z[1][4]=array();
$z[2]=Array("litpic","",178,193);
$z[2][4]=array();
$z[3]=Array("fulltitle","",256,274);
$z[3][4]=array();
$z[4]=Array("title","",375,389);
$z[4][4]=array();
$z[5]=Array("pubdate","",420,467);
$z[5][4]=array();
$z[5][4]['function']="MyDate('Y-m-d',@me)";
$z[6]=Array("description","",502,522);
$z[6][4]=array();

?>