<div class="m-news01 wow fadeInUp" data-wow-duration="1s" data-wow-delay=".5s"> <a href="[field:arcurl/]"  title="[field:fulltitle/]">
              <div class="pic"> <img src="[field:litpic/]" onerror="javascript:this.src='/skin/images/nopic.jpg';" alt="[field:fulltitle/]"> </div>
              <div class="txt">
                <div class="tit">
                  <h3>[field:title/]</h3>
                  <span>[field:pubdate function="MyDate('Y-m-d',@me)"/]</span> </div>
                <p>[field:description/]...</p>
              </div>
              </a> 
			</div>