<?php
$z[0]=Array("field","",224,255);
$z[0][4]=array();
$z[0][4]['name']="typenameen";
$z[1]=Array("field","",402,431);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("field","",664,693);
$z[2][4]=array();
$z[2][4]['name']="typename";
$z[3]=Array("field","",2019,2047);
$z[3][4]=array();
$z[3][4]['name']="typeurl";
$z[4]=Array("global","",2149,2170);
$z[4][4]=array();
$z[4][4]['name']="cfg_qq";

?>