<div id="floor_1_main">
    <div class="floor_1 w1200">
      <div class="in_title clearfix" aos="fade-up" aos-easing="ease" aos-duration="700">
        <p class="entit" aos="fade-up" aos-easing="ease" aos-duration="700">{dede:field name='typenameen'/}</p>
        <h3 class="tit clearfix" aos="fade-up" aos-easing="ease" aos-duration="700" aos-delay="100"><em class="line"></em><span class="word">{dede:field name='typename'/}</span><em class="line"></em></h3>
      </div>
      <div class="about clearfix" aos="fade-up" aos-easing="ease" aos-duration="700" aos-delay="100">
        <div class="item fl"><img class="img" src="/skin/images/about.jpg" alt="{dede:field name='typename'/}"/></div>
        <div class="contW fr">
          <p class="cont"> 广州市某某岗亭有限公司创建于1996年，地处广东省闻名中外的太湖之滨陶都宜兴，位于苏、浙、皖三省交界处，沪、宁、杭的中心，是一个文化发达的新兴城市，沪宜高速、宁杭高速、长深高速横穿而过，水陆交通十分便利。 公司专注于两大类化学品的开发、生产和营销： 广州市某某岗亭有限公司，专注建设停车场系统，打造交通设施，公路设施，、智能停车场收费管理系统，智能门禁，停车场道闸，停车场设施，停车场标识，监控系统等，主营产品还有与停车场系统相配套的各种材质的现代化岗亭；售货亭；报刊亭；治安岗亭；部队岗亭；高速公路收费岗亭；等岗亭系列产品；以及各种金属工程不锈钢厨窗、宣传栏、楼梯扶手、阳台护栏、旗杆；玻璃门、玻璃隔断。 专业承包各类金属工程，并可根据顾客不同的要求进行个性加工，提供让顾客满意的服务。我们将一如既往地追求:建精品工程，树企业丰碑的发展理念；秉承：至诚至信，服务至上，黄金品质，相融共生的经营理念；坚守：让人人...</p>
          <p class="view_detail fr"><a href="{dede:field name='typeurl'/}">查看详情</a></p>
          <p class="view_detail fr"><a  href="http://wpa.qq.com/msgrd?v=3&uin={dede:global.cfg_qq/}&site=qq&menu=yes">立即咨询</a></p>
        </div>
      </div>
    </div>
  </div>