<?php
$z[0]=Array("field","",224,255);
$z[0][4]=array();
$z[0][4]['name']="typenameen";
$z[1]=Array("field","",402,431);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("channel","  <a href=\"[field:typelink/]\" title=\"[field:typename/]\">[field:typename/]</a>",604,734);
$z[2][4]=array();
$z[2][4]['type']="son";
$z[2][4]['noself']="yes";
$z[3]=Array("arclist","\r\n		  <li><a href=\"[field:arcurl/]\" title=\"[field:title/]\"><img src=\"[field:litpic/]\" alt=\"[field:title/]\"/>\r\n            <div class=\"title clearfix\">\r\n              <h3 class=\"tit\" >[field:title/]</h3>\r\n            </div>\r\n            </a></li>\r\n			",919,1238);
$z[3][4]=array();
$z[3][4]['row']="8";
$z[3][4]['titlelen']="60";
$z[3][4]['orderby']="pubdate";
$z[4]=Array("field","",1430,1458);
$z[4][4]=array();
$z[4][4]['name']="typeurl";

?>