<?php
$z[0]=Array("field","",188,217);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("field","",257,289);
$z[1][4]=array();
$z[1][4]['name']="description";
$z[2]=Array("channel","\r\n            <li><a href=\"[field:typelink/]\" title=\"[field:typename/]\">[field:typename/]</a></li>\r\n            ",531,771);
$z[2][4]=array();
$z[2][4]['type']="son";
$z[2][4]['currentstyle']="<li><a href='~typelink~'>~typename~</a></li>";
$z[3]=Array("arclist","\r\n		  <dt><a href=\"[field:arcurl/]\" title=\"[field:title/]\"><img src=\"[field:litpic/]\" alt=\"[field:title/]\">\r\n            <p><span>[field:title/]</span><i class=\"icon\"></i></p>\r\n            <em><span>[field:title/]</span><s class=\"icon\"></s></em></a></dt>\r\n			",982,1314);
$z[3][4]=array();
$z[3][4]['limit']="0,1";
$z[3][4]['titlelen']="50";
$z[3][4]['orderby']="pubdate";
$z[4]=Array("arclist","\r\n			  <li class=\"item\"><a href=\"[field:arcurl/]\" title=\"[field:title/]\" class=\"a1\"><img src=\"[field:litpic/]\" alt=\"[field:title/]\">\r\n                <div class=\"d1\"><i class=\"icon\"></i>\r\n                  <h3>[field:title/]</h3>\r\n                </div>\r\n                </a></li>\r\n				",1404,1763);
$z[4][4]=array();
$z[4][4]['limit']="1,4";
$z[4][4]['titlelen']="50";
$z[4][4]['orderby']="pubdate";
$z[5]=Array("field","",1945,1973);
$z[5][4]=array();
$z[5][4]['name']="typeurl";

?>