<li class="animated flipInX"><a href="/a/qyxc/qyxc/54.html" title="农业机械农业机械" target="_blank"><img src="/uploads/allimg/181218/1-1Q21Q141330-L.jpg" width="235" height="160" alt="农业机械农业机械"/>
									<p>农业机械农业机械</p>
									</a></li>
<li class="animated flipInX"><a href="/a/qyxc/qyxc/53.html" title="园林景观石" target="_blank"><img src="/uploads/allimg/181218/1-1Q21Q141090-L.jpg" width="235" height="160" alt="园林景观石"/>
									<p>园林景观石</p>
									</a></li>
<li class="animated flipInX"><a href="/a/qyxc/qyxc/52.html" title=" 收割机收割机" target="_blank"><img src="/uploads/allimg/181218/1-1Q21Q140420-L.jpg" width="235" height="160" alt=" 收割机收割机"/>
									<p> 收割机收割机</p>
									</a></li>
<li class="animated flipInX"><a href="/a/qyxc/qyxc/51.html" title=" 温室大棚温室大棚" target="_blank"><img src="/uploads/allimg/181218/1-1Q21Q140100-L.jpg" width="235" height="160" alt=" 温室大棚温室大棚"/>
									<p> 温室大棚温室大棚</p>
									</a></li>

								</ul>
								</div>
							</div>
						</div>
					</div>
					<!-- End_Module_282373 -->
				</div>
			</div>
		</div>
	</div>
	<!-- E module-full-screen -->
	<!--S-->
	<div class="g-blk-news f-oh">
		<div class="container">
			<div class="m-box2 gs animated fadeInUp">
				<div class="m-hd">
					<h3>{dede:type typeid='13'}<a href="[field:typelink /]">[field:typename /]</a><span><a href="[field:typelink /]">更多&raquo;</a>{/dede:type}</span></h3>
				</div>
				<div class="m-bd">
					<ul class="m-txtlst1 ico2 hasline">
						{dede:arclist typeid='13' row='8' titlelen='60' orderby='pubdate'}
						<li><span>[[field:pubdate function="MyDate('Y-m-d',@me)"/]]</span><a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a></li>