<?php
$z[0]=Array("typelink","",1460,1478);
$z[0][4]=array();
$z[1]=Array("typename","",1480,1498);
$z[1][4]=array();
$z[2]=Array("typelink","",1517,1535);
$z[2][4]=array();
$z[3]=Array("pubdate","",1749,1796);
$z[3][4]=array();
$z[3][4]['function']="MyDate('Y-m-d',@me)";
$z[4]=Array("arcurl","",1813,1828);
$z[4][4]=array();
$z[5]=Array("title","",1837,1851);
$z[5][4]=array();
$z[6]=Array("title","",1853,1867);
$z[6][4]=array();

?>