<?php
$z[0]=Array("field","",4,35);
$z[0][4]=array();
$z[0][4]['name']="currentstyle";
$z[1]=Array("field","",47,73);
$z[1][4]=array();
$z[1][4]['name']="typeurl";
$z[2]=Array("field","",103,130);
$z[2][4]=array();
$z[2][4]['name']="typename";
$z[3]=Array("channel","\r\n            <dd><a href=\"[field:typeurl/]\">[field:typename/]</a></dd>\r\n			",158,272);
$z[3][4]=array();
$z[3][4]['type']="son";

?>