<?php
$z[0]=Array("field","",15,41);
$z[0][4]=array();
$z[0][4]['name']="currentstyle";
$z[1]=Array("field","",49,77);
$z[1][4]=array();
$z[1][4]['name']="typeurl";
$z[2]=Array("field","",94,123);
$z[2][4]=array();
$z[2][4]['name']="typename";
$z[3]=Array("channel","\r\n            <dd><a href=\"[field:typelink/]\" title=\"[field:typename/]\">[field:typename/]</a></dd>\r\n             ",181,347);
$z[3][4]=array();
$z[3][4]['type']="son";
$z[3][4]['noself']="yes";

?>