<div class="about_serv" style="background-image: url(/skin/images/about.jpg); background-size: cover;">
	<div class="container">
		<div class="row">
			<div class="col-xs-12 col-sm-6 col-md-6 left col">
			</div>
			<div class="col-xs-12 col-sm-6 col-md-6 about_right">
				<h2>{dede:field name='typename'/}</h2>
				<p>{dede:field name='typenameen'/}</p>
				<p class="about_contents">
					 百度，全球最大的中文搜索引擎、最大的中文网站。1999年底，身在美国硅谷的李彦宏看到了中国互联网及中文搜索引擎服务的巨大发展潜力，抱着技术改变世界的梦想，他毅然辞掉硅谷的高薪工作，携搜索引擎专利技术，于2000年1月1日在中关村创建了百度公司。 百度二字，来自于八百年前南宋词人辛弃疾的一句词：众里寻他千百度。这句话描述了词人对理想的执着追求。 百度拥有数万名研发工程师，这是中国乃至...
				</p>
				<p>
				</p>
				<a href="/a/gywm/" class="about_btn">MORE</a>
			</div>
		</div>
	</div>
</div>