<?php
$z[0]=Array("field","",121,150);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("arclist","<li><a href=\"view.php?aid=[field:id/]\" title=\"[field:title/]\">\r\n            <div class=\"img\"><img class=\"img\" src=\"[field:litpic/]\" alt=\"[field:title/]\"/></div>\r\n            <div class=\"txt\">\r\n              <h3 class=\"tit\" >[field:title/]</h3>\r\n              <p class=\"cont\">[field:description function=\"cn_substr(@me,80)\"/]...</p>\r\n            </div>\r\n            </a></li>\r\n			",272,731);
$z[1][4]=array();
$z[1][4]['typeid']="";
$z[1][4]['row']="10";
$z[1][4]['titlelen']="50";
$z[1][4]['orderby']="pubdate";
$z[2]=Array("field","",894,917);
$z[2][4]=array();
$z[2][4]['name']="id";

?>