<?php
$z[0]=Array("field","",138,167);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("field","",192,224);
$z[1][4]=array();
$z[1][4]['name']="description";
$z[2]=Array("channel","\r\n		<dl class=\"dl[field:global name=autoindex runphp=\"yes\"]@me=@me+1;[/field:global]\">\r\n          <a href=\"list.php?tid=[field:id/]\" title=\"[field:typename/]\">\r\n          <dt><img src=\"/m/skin/images/fw[field:global name=autoindex runphp=\"yes\"]@me=@me+1;[/field:global].jpg\"  alt=\"[field:typename/]\"></dt>\r\n          <dd><i></i>\r\n            <h3>[field:typename/]<span></span></h3>\r\n            <p>[field:typename/]</p>\r\n          </dd>\r\n          </a>\r\n        </dl>\r\n        ",276,809);
$z[2][4]=array();
$z[2][4]['type']="son";
$z[2][4]['currentstyle']="";
$z[3]=Array("field","",883,906);
$z[3][4]=array();
$z[3][4]['name']="id";

?>