<?php
$z[0]=Array("field","",128,156);
$z[0][4]=array();
$z[0][4]['name']="typeimg";
$z[1]=Array("field","",200,229);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("field","",240,271);
$z[2][4]=array();
$z[2][4]['name']="typenameen";
$z[3]=Array("arclist","\r\n			<li>\r\n              <h5><span>问</span>：[field:title/]</h5>\r\n              <p><span>答：</span>[field:description function=\"cn_substr(@me,300)\"/]... </p>\r\n            </li>\r\n			",317,584);
$z[3][4]=array();
$z[3][4]['typeid']="";
$z[3][4]['row']="10";
$z[3][4]['titlelen']="60";
$z[3][4]['orderby']="pubdate";

?>