<div class="inews2" aos="fade-left" aos-easing="ease" aos-duration="700" aos-delay="100"> <div class="title"><a class="more fr" href="{dede:field name='typeurl'/}"  title="更多+">更多+</a>
          <h3><s></s>{dede:field name='typename'/}</h3>
        </div>
        <ul class="newslist">
          {dede:arclist row='8' titlelen='50' orderby='pubdate'}
		  <li><a href="[field:arcurl/]" title="[field:title/]"><span class="time">2019-11-06</span>[field:title/]</a></li>
		  {/dede:arclist}
        </ul>
      </div>