<?php
$z[0]=Array("field","",134,162);
$z[0][4]=array();
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",215,244);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("arclist","\r\n		  <li><a href=\"[field:arcurl/]\" title=\"[field:title/]\"><span class=\"time\">2019-11-06</span>[field:title/]</a></li>\r\n		  ",308,501);
$z[2][4]=array();
$z[2][4]['row']="8";
$z[2][4]['titlelen']="50";
$z[2][4]['orderby']="pubdate";

?>