<li class="item it7" aos='fade-right' aos-easing="ease" aos-duration="700" aos-delay="100"><a>
              <h2><i class="icon"></i>[field:typenameen /]</h2>
              <p>[field:description /]</p>
              </a></li>
            {dede:type typeid='36'}
            <li class="item it8" aos='fade-left' aos-easing="ease" aos-duration="700" aos-delay="100"><a>
              <h2><i class="icon"></i>[field:typenameen /]</h2>
              <p>[field:description /]</p>
              </a></li>