<li class="clearfix" aos="fade-up" aos-easing="ease" aos-duration="700" aos-delay="100"><a href="[field:arcurl/]" title="[field:title/]"><span class="left box1"><img src="[field:litpic/]" alt="[field:title/]"></span><span class="left box2">
            <h1>[field:title/]</h1>
            <p>[field:description function="cn_substr(@me,200)"/]...</p>
            <span>阅读量：[field:click/]</span></span><span class="right">
            <h3>[field:pubdate function="MyDate('m-d',@me)"/]</h3>
            <p>[field:pubdate function="MyDate('Y',@me)"/]</p>
            </span></a></li>