<?php
$z[0]=Array("field","",193,224);
$z[0][4]=array();
$z[0][4]['name']="typenameen";
$z[1]=Array("field","",496,524);
$z[1][4]=array();
$z[1][4]['name']="typeurl";
$z[2]=Array("channel","\r\n            <li class=\"item\"><a href=\"[field:typelink/]\" title=\"[field:typename/]\">[field:typename/]</a></li>\r\n            ",555,733);
$z[2][4]=array();
$z[2][4]['type']="son";
$z[2][4]['noself']="yes";
$z[3]=Array("arclist","\r\n			  <li class=\"item\"><a href=\"[field:arcurl/]\" title=\"[field:title/]\"><img src=\"[field:litpic/]\" alt=\"[field:title/]\"/>\r\n                <p>[field:title/]</p>\r\n                <div class=\"bg\"></div>\r\n                <div class=\"txtIco\"><s class=\"icon\"></s></div>\r\n                </a></li>\r\n				",1008,1376);
$z[3][4]=array();
$z[3][4]['row']="10";
$z[3][4]['titlelen']="60";
$z[3][4]['orderby']="pubdate";
$z[4]=Array("field","",1483,1511);
$z[4][4]=array();
$z[4][4]['name']="typeurl";

?>