<div class="a1 w1204">
	<div class="a_t">
		<span>{dede:field name='typename'/}</span>{dede:field name='typenameen'/}
	</div>
	<div class="c2a">
		<div class="tabli">
			<ul class="a1_ul">
				<li><a href="/gcal/">全部</a></li>
				
				<li class="layer1"><a href='/gcal/alfl1/'>案例分类1</a></li>
				
				<li class="layer1"><a href='/gcal/alfl2/'>案例分类2</a></li>
				
				<li class="layer1"><a href='/gcal/alfl3/'>案例分类3</a></li>
				
				<li class="layer1"><a href='/gcal/alfl4/'>案例分类4</a></li>
				
				<li class="layer1"><a href='/gcal/alfl5/'>案例分类5</a></li>
				
				<li class="layer1"><a href='/gcal/alfl6/'>案例分类6</a></li>
				
				<li class="layer1"><a href='/gcal/alfl7/'>案例分类7</a></li>
				
			</ul>
		</div>
	</div>
</div>