<?php
$z[0]=Array("field","",125,154);
$z[0][4]=array();
$z[0][4]['name']="typenameen";
$z[1]=Array("field","",167,193);
$z[1][4]=array();
$z[1][4]['name']="typeurl";
$z[2]=Array("field","",202,229);
$z[2][4]=array();
$z[2][4]['name']="typename";
$z[3]=Array("field","",231,258);
$z[3][4]=array();
$z[3][4]['name']="typename";
$z[4]=Array("arclist","\r\n        <div class=\"in_news_t anim anim-1\">\r\n            <div class=\"in_news_t_l\"><a href=\"[field:arcurl/]\" title=\"[field:fulltitle/]\" class=\"img\"><img src=\"[field:litpic/]\" alt=\"[field:fulltitle/]\"></a></div>\r\n            <div class=\"in_news_t_r\"><a href=\"[field:arcurl/]\" title=\"[field:fulltitle/]\">[field:title/]</a><span>[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</span>\r\n                <p>[field:description/]...</p>\r\n                <h3><a href=\"[field:arcurl/]\">READ MORE +</a></h3>\r\n            </div>\r\n        </div>\r\n        <!--推荐内容结束-->\r\n		",307,934);
$z[4][4]=array();
$z[4][4]['row']="1";
$z[4][4]['flag']="c";
$z[4][4]['titlelen']="100";
$z[5]=Array("arclist","\r\n            <div class=\"in_news_list\">\r\n                <h4><a href=\"[field:arcurl/]\" title=\"[field:fulltitle/]\" class=\"img\"><img src=\"[field:litpic/]\" alt=\"[field:fulltitle/]\"></a></h4>\r\n                <h5><a href=\"[field:arcurl/]\" title=\"[field:fulltitle/]\">[field:title/]</a><span>[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</span>\r\n                    <p>[field:description/]...</p>\r\n                </h5>\r\n            </div>\r\n			",1020,1518);
$z[5][4]=array();
$z[5][4]['row']="4";
$z[5][4]['noflag']="c";
$z[5][4]['titlelen']="100";

?>