<?php
$z[0]=Array("field","",135,163);
$z[0][4]=array();
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",216,245);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("arclist","\r\n			  <li class=\"item\"><a href=\"[field:arcurl/]\" title=\"[field:title/]\"><img src=\"[field:litpic/]\" alt=\"[field:title/]\"/>\r\n                <div class=\"txtcon\">\r\n                  <h3>[field:title/]</h3>\r\n                </div>\r\n                </a></li>\r\n				",419,748);
$z[2][4]=array();
$z[2][4]['row']="8";
$z[2][4]['titlelen']="50";
$z[2][4]['orderby']="pubdate";
$z[3]=Array("arclist","\r\n		  <li><a href=\"[field:arcurl/]\" title=\"[field:title/]\" ><span class=\"time\">[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</span>[field:title/]</a></li>\r\n		  ",976,1207);
$z[3][4]=array();
$z[3][4]['row']="8";
$z[3][4]['titlelen']="50";
$z[3][4]['orderby']="pubdate";

?>