<?php
$z[0]=Array("field","",54,83);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("field","",95,127);
$z[1][4]=array();
$z[1][4]['name']="description";
$z[2]=Array("field","",162,193);
$z[2][4]=array();
$z[2][4]['name']="typenameen";
$z[3]=Array("arclist","\r\n  <div class=\"col-xs-12 col-sm-4 col-md-4 \">\r\n		<div class=\"recent-work-wrap\">\r\n		  <a href=\"[field:arcurl/]\">\r\n		  <img class=\"img-responsive\" src=\"[field:litpic/]\" alt=\"[field:title/]\">\r\n			  <div class=\"overlay\">\r\n					<div class=\"recent-work-inner\">\r\n					  <h3>[field:title/]</h3>\r\n					  <p>[field:description function=\"cn_substr(@me,300)\"/]</p>\r\n					</div>\r\n			  </div>\r\n		   </a>\r\n		</div>\r\n  </div>\r\n  ",337,830);
$z[3][4]=array();
$z[3][4]['typeid']="";
$z[3][4]['row']="6";
$z[3][4]['titlelen']="60";
$z[3][4]['orderby']="pubdate";
$z[4]=Array("field","",851,879);
$z[4][4]=array();
$z[4][4]['name']="typeurl";

?>