<?php
$z[0]=Array("field","",155,183);
$z[0][4]=array();
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",192,221);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("field","",223,252);
$z[2][4]=array();
$z[2][4]['name']="typename";
$z[3]=Array("field","",282,310);
$z[3][4]=array();
$z[3][4]['name']="typeurl";
$z[4]=Array("arclist","\r\n		  <a href=\"[field:arcurl/]\" title=\"[field:title/]\">\r\n          <div class=\"xxxw\">\r\n            <div class=\"xwtp1\"><img src=\"[field:litpic/]\" alt=\"[field:title/]\" width=\"210\" height=\"158\"/></div>\r\n            <div class=\"xwwz1\">\r\n              <h3 >[field:title/]</h3>\r\n              <p>[field:description function=\"cn_substr(@me,200)\"/]...</p>\r\n              <span>[查看详情]</span></div>\r\n          </div>\r\n          </a>\r\n		  ",424,943);
$z[4][4]=array();
$z[4][4]['typeid']="";
$z[4][4]['limit']="0,1";
$z[4][4]['titlelen']="50";
$z[4][4]['orderby']="pubdate";
$z[5]=Array("arclist","\r\n			<li><a href=\"[field:arcurl/]\" title=\"[field:title/]\" >[field:title/]</a><span>[[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]]</span></li>\r\n			",1042,1274);
$z[5][4]=array();
$z[5][4]['typeid']="";
$z[5][4]['limit']="1,5";
$z[5][4]['titlelen']="50";
$z[5][4]['orderby']="pubdate";

?>