<?php
$z[0]=Array("field","",189,218);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("channel"," <a href=\"list.php?tid=[field:id/]\" title=\"[field:typename/]\">[field:typename/]</a> ",328,520);
$z[1][4]=array();
$z[1][4]['type']="son";
$z[1][4]['row']="6";
$z[1][4]['currentstyle']="<a href='list.php?tid=~id~'>~typename~</a>";
$z[2]=Array("arclist","\r\n          <li><a href=\"view.php?aid=[field:id/]\" title=\"[field:title/]\">\r\n            <h3 class=\"tit\" >[field:title/]</h3>\r\n            <p class=\"time\">[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</p>\r\n            </a></li>\r\n          ",626,935);
$z[2][4]=array();
$z[2][4]['row']="5";
$z[2][4]['titlelen']="50";
$z[2][4]['orderby']="pubdate";
$z[3]=Array("field","",1000,1023);
$z[3][4]=array();
$z[3][4]['name']="id";

?>