<?php
$z[0]=Array("field","",188,217);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("field","",257,289);
$z[1][4]=array();
$z[1][4]['name']="description";
$z[2]=Array("channel","\r\n            <li><a href=\"[field:typelink/]\" title=\"[field:typename/]\">[field:typename/]</a></li>\r\n            ",531,771);
$z[2][4]=array();
$z[2][4]['type']="son";
$z[2][4]['currentstyle']="<li><a href='~typelink~'>~typename~</a></li>";
$z[3]=Array("arclist","\r\n		  <dt><a href=\"[field:arcurl/]\" title=\"[field:title/]\"><img src=\"[field:litpic/]\" alt=\"[field:title/]\">\r\n            <p><span>[field:title/]</span><i class=\"icon\"></i></p>\r\n            <em><span>[field:title/]</span><s class=\"icon\"></s></em></a></dt>\r\n			",982,1314);
$z[3][4]=array();
$z[3][4]['limit']="0,1";
$z[3][4]['titlelen']="50";
$z[3][4]['orderby']="pubdate";

?>