<?php
$z[0]=Array("field","",155,183);
$z[0][4]=array();
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",192,221);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("field","",223,252);
$z[2][4]=array();
$z[2][4]['name']="typename";
$z[3]=Array("field","",282,310);
$z[3][4]=array();
$z[3][4]['name']="typeurl";
$z[4]=Array("arclist","\r\n		  <li class='on'><a href=\"[field:arcurl/]\" title=\"[field:title/]\"  >[field:title/]</a>\r\n            <div class=\"news_nextNav\">\r\n              <p>[field:description function=\"cn_substr(@me,200)\"/]...<a href=\"[field:arcurl/]\" title=\"[查看详情]\">[查看详情]</a></p>\r\n            </div>\r\n          </li>\r\n		  ",367,762);
$z[4][4]=array();
$z[4][4]['typeid']="";
$z[4][4]['row']="6";
$z[4][4]['titlelen']="50";
$z[4][4]['orderby']="pubdate";

?>