<?php
$z[0]=Array("field","",126,155);
$z[0][4]=array();
$z[0][4]['name']="typenameen";
$z[1]=Array("field","",168,194);
$z[1][4]=array();
$z[1][4]['name']="typeurl";
$z[2]=Array("field","",203,230);
$z[2][4]=array();
$z[2][4]['name']="typename";
$z[3]=Array("field","",232,259);
$z[3][4]=array();
$z[3][4]['name']="typename";
$z[4]=Array("arclist","\r\n                <li><a href=\"[field:arcurl/]\" title=\"[field:fulltitle/]\">\r\n                    <div class=\"img\"><img src=\"[field:litpic/]\" alt=\"[field:fulltitle/]\"></div>\r\n                    <p class=\"trans\" >[field:title/]</p>\r\n                    </a></li>\r\n				",339,654);
$z[4][4]=array();
$z[4][4]['row']="4";
$z[4][4]['titlelen']="100";

?>