<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]=array();
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/191231/1-191231201S1.jpg ",93,238);
$z[1][4]=array();
$z[1][4]['ddimg']="/uploads/allimg/191231/1-191231201S1.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="640";
$z[1][4]['height']="480";
$z[2]=Array("img"," /uploads/allimg/191231/1-191231201S4.jpg ",240,385);
$z[2][4]=array();
$z[2][4]['ddimg']="/uploads/allimg/191231/1-191231201S4.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="640";
$z[2][4]['height']="480";
$z[3]=Array("img"," /uploads/allimg/191231/1-191231201S4-50.jpg ",387,538);
$z[3][4]=array();
$z[3][4]['ddimg']="/uploads/allimg/191231/1-191231201S4-50.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="640";
$z[3][4]['height']="480";

?>