
<field:name itemname="姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:name>

<field:tel itemname="电话" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:tel>

<field:content itemname="留言内容" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:content>

<field:titles itemname="留言标题" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:titles>

<field:email itemname="电子邮箱" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:email>

<field:address itemname="联系地址" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:address>

<field:mytime itemname="留言时间" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:mytime>
