<?php
$z[0]=Array("global","\r\n                      \$a=\"\";\r\n                        \$b=\" hover\";\r\n                        if ((@me%0)==0 && @me!=0)  @me=\$a;\r\n                        else  @me=\$b;\r\n                        ",29,279);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[0][4]['name']="autoindex";
$z[1]=Array("typelink","",290,307);
$z[1][4]=array();
$z[2]=Array("typename","",316,333);
$z[2][4]=array();
$z[3]=Array("typename","",335,352);
$z[3][4]=array();

?>