<?php
$z[0]=Array("field","",135,163);
$z[0][4]=array();
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",172,201);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("field","",203,232);
$z[2][4]=array();
$z[2][4]['name']="typename";
$z[3]=Array("arclist","\r\n		  <li><a href=\"[field:arcurl/]\" title=\"[field:title/]\"><img src=\"[field:litpic/]\" alt=\"[field:title/]\"><span >[field:title/]</span></a></li>\r\n		  ",292,522);
$z[3][4]=array();
$z[3][4]['typeid']="";
$z[3][4]['row']="10";
$z[3][4]['titlelen']="50";
$z[3][4]['orderby']="pubdate";

?>