<?php
$z[0]=Array("field","",192,221);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("channel"," <a href=\"list.php?tid=[field:id/]\" title=\"[field:typename/]\">[field:typename/]</a> ",331,523);
$z[1][4]=array();
$z[1][4]['type']="son";
$z[1][4]['row']="6";
$z[1][4]['currentstyle']="<a href='list.php?tid=~id~'>~typename~</a>";
$z[2]=Array("arclist","\r\n          <li><a href=\"view.php?aid=[field:id/]\" title=\"[field:title/]\">\r\n            <div class=\"img\"><img class=\"img\" src=\"[field:picname/]\" alt=\"[field:title/]\"/></div>\r\n            <div class=\"txt\">\r\n              <h3 class=\"tit\" >[field:title/]</h3>\r\n            </div>\r\n            <p class=\"detail\">详情>></p>\r\n            </a></li>\r\n          ",642,1066);
$z[2][4]=array();
$z[2][4]['row']="6";
$z[2][4]['titlelen']="50";
$z[2][4]['orderby']="pubdate";
$z[3]=Array("field","",1143,1166);
$z[3][4]=array();
$z[3][4]['name']="id";

?>