<?php
$z[0]=Array("field","",128,156);
$z[0][4]=array();
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",200,229);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("field","",240,271);
$z[2][4]=array();
$z[2][4]['name']="typenameen";
$z[3]=Array("field","",320,348);
$z[3][4]=array();
$z[3][4]['name']="typeimg";
$z[4]=Array("field","",355,384);
$z[4][4]=array();
$z[4][4]['name']="typename";
$z[5]=Array("arclist","\r\n			<li><a href=\"[field:arcurl/]\"  title=\"[field:title/]\"><span>【[field:typename/]】</span>[field:title/]</a></li>\r\n			",470,673);
$z[5][4]=array();
$z[5][4]['typeid']="";
$z[5][4]['row']="10";
$z[5][4]['titlelen']="60";
$z[5][4]['orderby']="pubdate";

?>