<?php
$z[0]=Array("field","",121,150);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("channel","<a href=\"list.php?tid=[field:id/]\" title=\"[field:typename/]\">[field:typename/]</a>  ",261,398);
$z[1][4]=array();
$z[1][4]['type']="son";
$z[1][4]['noself']="yes";
$z[2]=Array("arclist","\r\n		  <li><a href=\"view.php?aid=[field:id/]\" title=\"[field:title/]\">\r\n            <div class=\"img\"><img class=\"img\" src=\"[field:litpic/]\" alt=\"[field:title/]\"/></div>\r\n            <h3 class=\"tit\">[field:title/]</h3>\r\n            </a></li>\r\n			",516,838);
$z[2][4]=array();
$z[2][4]['typeid']="";
$z[2][4]['row']="6";
$z[2][4]['titlelen']="50";
$z[2][4]['orderby']="pubdate";

?>