<?php
$z[0]=Array("field","",188,217);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("field","",257,289);
$z[1][4]=array();
$z[1][4]['name']="description";
$z[2]=Array("channel","\r\n            <li><a href=\"[field:typelink/]\" title=\"[field:typename/]\">[field:typename/]</a></li>\r\n            ",531,771);
$z[2][4]=array();
$z[2][4]['type']="son";
$z[2][4]['currentstyle']="<li><a href='~typelink~'>~typename~</a></li>";

?>