<div class="floor_1_main">
    <div class="w1200 clearfix">
      <div class="indexTit" aos="fade-up" aos-easing="ease" aos-duration="700">
        <h3 class="tit">某某公司 ·<span>{dede:field name='typename'/}</span></h3>
        <p class="subtit">{dede:field name='description'/}</p>
      </div>
      <div class="floor_1"> 
        <!--产品分类开始-->
        <div class="menu hd clearfix" aos="fade-up" aos-easing="ease" aos-duration="700" aos-delay="200">
          <ul class="list clearfix">
            {dede:channel type='son' currentstyle="
            <li><a href='~typelink~'>~typename~</a></li>
            "}
            <li><a href="[field:typelink/]" title="[field:typename/]">[field:typename/]</a></li>
            {/dede:channel}            
          </ul>
        </div>
        <!--产品分类结束-->
        <dl aos="fade-up" aos-easing="ease" aos-duration="700" aos-delay="300">
          <!--推荐内容开始--> 
          <dt><a href="/a/chanpinzhongxin/cp1/18.html" title="产品中心标题六"><img src="/uploads/allimg/190109/1-1Z10ZU3150-L.jpg" alt="产品中心标题六">
            <p><span>产品中心标题六</span><i class="icon"></i></p>
            <em><span>产品中心标题六</span><s class="icon"></s></em></a></dt>
 
          <!--推荐内容结束-->
          <dd>
            <ul>
              <li class="item"><a href="/a/chanpinzhongxin/cp1/17.html" title="产品中心标题五" class="a1"><img src="/uploads/allimg/190109/1-1Z10ZU2400-L.jpg" alt="产品中心标题五">
                <div class="d1"><i class="icon"></i>
                  <h3>产品中心标题五</h3>
                </div>
                </a></li>
<li class="item"><a href="/a/chanpinzhongxin/cp1/16.html" title="产品中心标题四" class="a1"><img src="/uploads/allimg/190109/1-1Z10ZU2190-L.jpg" alt="产品中心标题四">
                <div class="d1"><i class="icon"></i>
                  <h3>产品中心标题四</h3>
                </div>
                </a></li>
<li class="item"><a href="/a/chanpinzhongxin/cp1/15.html" title="产品中心标题三" class="a1"><img src="/uploads/allimg/190109/1-1Z10ZU1310-L.jpg" alt="产品中心标题三">
                <div class="d1"><i class="icon"></i>
                  <h3>产品中心标题三</h3>
                </div>
                </a></li>
<li class="item"><a href="/a/chanpinzhongxin/cp1/14.html" title="产品中心标题二" class="a1"><img src="/uploads/allimg/190109/1-1Z10ZT9470-L.jpg" alt="产品中心标题二">
                <div class="d1"><i class="icon"></i>
                  <h3>产品中心标题二</h3>
                </div>
                </a></li>

            </ul>
          </dd>
        </dl>
      </div>
      <div class="floor_5_2" aos="fade-up" aos-easing="ease" aos-duration="700" style="margin-top: 50px;"><a href="/a/chanpinzhongxin/" title="查看更多">查看更多 &gt;&gt;</a></div>
    </div>
  </div>