<?php
$z[0]=Array("field","",109,136);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("arclist","\r\n        <div class=\"item\"><a href=\"[field:arcurl/]\"  title=\"[field:fulltitle/]\">\r\n          <div class=\"txt\">\r\n            <h3>[field:title/]</h3>\r\n            <span>[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</span>\r\n            <p>[field:description/]...</p>\r\n          </div>\r\n          </a> </div>\r\n		",241,601);
$z[1][4]=array();
$z[1][4]['row']="12";
$z[1][4]['titlelen']="100";

?>