<div class="row-a7">
    <div class="wp">
      <h3>轴承实业</h3>
      <h3>务实-创新-追求卓越</h3>
        <div class="pic wow fadeInUp" data-wow-duration="1s" data-wow-delay=".1s"><img src="{dede:field name='typeimg'/}" alt="{dede:field name='typename'/}"></div>
        <div class="txt wow fadeInUp" data-wow-duration="1s" data-wow-delay=".1s">
			<p style="white-space: normal;">　  {dede:sql sql='Select content from dede_arctype where id=16'} 
        [field:content  function='cn_substr(html2text(@me),570)'/]
        {/dede:sql}...</p>
		</div>
       <a class="more wow fadeInUp" data-wow-duration="1s" data-wow-delay=".1s" href="{dede:field name='typeurl'/}">了解更多</a>
    </div>
  </div>