<?php
$z[0]=Array("global","\r\n                      \$a=\"\";\r\n                        \$b=\" active\";\r\n                        if ((@me%1)==0 && @me!=1)  @me=\$a;\r\n                        else  @me=\$b;\r\n                        ",16,267);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[0][4]['name']="autoindex";
$z[1]=Array("pic","",283,295);
$z[1][4]=array();
$z[2]=Array("title","",302,316);
$z[2][4]=array();

?>