






<field:ptitle itemname="留言标题" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:ptitle>

<field:name itemname="联系人" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:name>

<field:contact itemname="电话" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:contact>

<field:email itemname="邮箱" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:email>

<field:address itemname="地址" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:address>

<field:content itemname="留言内容" autofield="1" type="multitext" isnull="true" default=""  maxlength="250" page="">
</field:content>
