<?php
$z[0]=Array("field","",190,218);
$z[0][4]=array();
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",227,256);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("field","",258,287);
$z[2][4]=array();
$z[2][4]['name']="typename";
$z[3]=Array("arclist","\r\n			<li><a href=\"[field:arcurl/]\" title=\"[field:title/]\"><img src=\"[field:litpic/]\" alt=\"[field:title/]\"><span >[field:title/]</span>\r\n              <p>[field:description function=\"cn_substr(@me,200)\"/]...</p>\r\n              <i></i></a></li>\r\n			  ",419,748);
$z[3][4]=array();
$z[3][4]['typeid']="";
$z[3][4]['row']="10";
$z[3][4]['titlelen']="50";
$z[3][4]['orderby']="pubdate";

?>