<?php
$z[0]=Array("field","",171,200);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("sql"," \r\n        [field:content  function='cn_substr(html2text(@me),500)'/]\r\n        ",250,400);
$z[1][4]=array();
$z[1][4]['sql']="Select content from dede_arctype where id=1";
$z[2]=Array("field","",430,458);
$z[2][4]=array();
$z[2][4]['name']="typeurl";
$z[3]=Array("field","",688,717);
$z[3][4]=array();
$z[3][4]['name']="typename";

?>