<?php
$z[0]=Array("field","",179,210);
$z[0][4]=array();
$z[0][4]['name']="typenameen";
$z[1]=Array("channel","\r\n	  <a class=\"item\" href=\"[field:typelink/]\" title=\"[field:typename/]\">[field:typename/]</a> \r\n	    ",408,562);
$z[1][4]=array();
$z[1][4]['type']="son";
$z[1][4]['noself']="yes";
$z[2]=Array("arclist","\r\n            <dd class=\"d[field:global runphp='yes' name=autoindex][/field:global]\">\r\n              <div class=\"box1\"><a href=\"[field:arcurl/]\" title=\"[field:title/]\">\r\n                <h3>[field:title/]</h3>\r\n                <p>产品以再生废纸、芦苇浆、甘蔗浆、植物桔杆、果壳等为原料,可完全回收再生利用。~再生废纸、植物桔杆等为原料 产品原料和成品弃置后...</p>\r\n                <i class=\"icon\"></i><span class=\"icon\"></span></a></div>\r\n              <div class=\"box2\"><a href=\"[field:arcurl/]\" title=\"[field:title/]\"><img src=\"[field:litpic/]\" alt=\"[field:title/]\"></a></div>\r\n            </dd>\r\n  ",743,1483);
$z[2][4]=array();
$z[2][4]['typeid']="6";
$z[2][4]['row']="2";
$z[2][4]['titlelen']="60";
$z[2][4]['orderby']="pubdate";
$z[3]=Array("arclist","\r\n                <li class=\"item\"><a href=\"[field:arcurl/]\" title=\"[field:title/]\">\r\n                  <div class=\"img\"><img src=\"[field:litpic/]\" alt=\"[field:title/]\"/></div>\r\n                  <div class=\"txt\">\r\n                    <h3 class=\"tit\">[field:title/]</h3>\r\n                  </div>\r\n                  </a></li>\r\n  ",1761,2181);
$z[3][4]=array();
$z[3][4]['row']="5";
$z[3][4]['titlelen']="60";
$z[3][4]['orderby']="pubdate";
$z[3][4]['typeid']="6";
$z[3][4]['flag']="h";

?>