<?php
$z[0]=Array("field","",105,134);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("field","",157,189);
$z[1][4]=array();
$z[1][4]['name']="description";
$z[2]=Array("channel","\r\n          <li><a href=\"list.php?tid=[field:id/]\" title=\"[field:typename/]\">[field:typename/]</a></li>\r\n          ",360,606);
$z[2][4]=array();
$z[2][4]['type']="son";
$z[2][4]['currentstyle']="<li><a href='list.php?tid=~id~'>~typename~</a></li>";
$z[3]=Array("arclist","\r\n			<li class=\"item\"><a href=\"view.php?aid=[field:id/]\" title=\"[field:title/]\">\r\n              <figure><img src=\"[field:litpic/]\" alt=\"[field:title/]\"/></figure>\r\n              <h3>[field:title/]</h3>\r\n              </a></li>\r\n			  ",789,1091);
$z[3][4]=array();
$z[3][4]['row']="6";
$z[3][4]['titlelen']="50";
$z[3][4]['orderby']="pubdate";
$z[4]=Array("field","",1195,1218);
$z[4][4]=array();
$z[4][4]['name']="id";

?>