<?php
$z[0]=Array("field","",134,163);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("field","",188,220);
$z[1][4]=array();
$z[1][4]['name']="description";
$z[2]=Array("field","",305,334);
$z[2][4]=array();
$z[2][4]['name']="typename";
$z[3]=Array("sql"," \r\n        [field:content  function='cn_substr(html2text(@me),500)'/]\r\n        ",361,511);
$z[3][4]=array();
$z[3][4]['sql']="Select content from dede_arctype where id=1";
$z[4]=Array("field","",578,601);
$z[4][4]=array();
$z[4][4]['name']="id";

?>