<?php
$z[0]=Array("field","",71,100);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("field","",136,159);
$z[1][4]=array();
$z[1][4]['name']="id";
$z[2]=Array("arclist","\r\n						<li>\r\n                <a href=\"view.php?aid=[field:id/]\" title=\"[field:title/]\">\r\n                        [field:title/]\r\n                        <span>[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</span>\r\n                </a>\r\n\r\n            </li>\r\n			",248,579);
$z[2][4]=array();
$z[2][4]['row']="6";
$z[2][4]['titlelen']="50";
$z[2][4]['orderby']="pubdate";

?>