<?php
$z[0]=Array("field","",284,313);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("field","",327,358);
$z[1][4]=array();
$z[1][4]['name']="typenameen";
$z[2]=Array("sql"," \r\n        [field:content  function='cn_substr(html2text(@me),550)'/]\r\n        ",402,552);
$z[2][4]=array();
$z[2][4]['sql']="Select content from dede_arctype where id=1";
$z[3]=Array("field","",599,627);
$z[3][4]=array();
$z[3][4]['name']="typeurl";

?>