<div class="floor_4 clearfix">
    <div class="floor_4_main w1200">
      <div class="txt">
        <h2 class="tit" aos="fade-up" aos-easing="ease" aos-duration="700" aos-delay="100">{dede:field name='typename'/}</h2>
        <i class="icon" aos="fade-up" aos-easing="ease" aos-duration="700" aos-delay="100"></i>
        <p class="p1" aos="fade-up" aos-easing="ease" aos-duration="700" aos-delay="200">　　 {dede:sql sql='Select content from dede_arctype where id=1'} 
        [field:content  function='cn_substr(html2text(@me),1200)'/]
        {/dede:sql}...</p>
        <a href="/a/anli/" aos="fade-up" aos-easing="ease" aos-duration="700" aos-delay="300">了解更多</a></div>
    </div>
  </div>