<?php
$z[0]=Array("arcurl","",47,62);
$z[0][4]=array();
$z[1]=Array("fulltitle","",71,89);
$z[1][4]=array();
$z[2]=Array("litpic","",180,195);
$z[2][4]=array();
$z[3]=Array("fulltitle","",202,220);
$z[3][4]=array();
$z[4]=Array("title","",318,332);
$z[4][4]=array();
$z[5]=Array("pubdate","",365,412);
$z[5][4]=array();
$z[5][4]['function']="MyDate('Y-m-d',@me)";
$z[6]=Array("description","",444,464);
$z[6][4]=array();

?>