<div class="ny_news_list anim anim-1"><a href="[field:arcurl/]" title="[field:fulltitle/]">
                <div class="n_news_l">
                    <div class="img"><img src="[field:litpic/]" alt="[field:fulltitle/]"></div>
                </div>
                <div class="n_news_r">
                    <h3>[field:title/]</h3>
                    <span>[field:pubdate function="MyDate('Y-m-d',@me)"/]</span>
                    <p>[field:description/]...</p>
                </div>
                </a></div>