<?php
$z[0]=Array("field","",63,91);
$z[0][4]=array();
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",100,129);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("field","",131,160);
$z[2][4]=array();
$z[2][4]['name']="typename";
$z[3]=Array("arclist","\r\n						<li><a href=\"[field:arcurl/]\"><span class=\"iconfont icon-jiantou\"></span>[field:title/]</a></li>\r\n						",203,352);
$z[3][4]=array();
$z[3][4]['row']="5";

?>