
		<dl class="dl[field:global name=autoindex runphp="yes"]@me=@me+1;[/field:global]">
          <a href="list.php?tid=[field:id/]" title="[field:typename/]">
          <dt><img src="/m/skin/images/fw[field:global name=autoindex runphp="yes"]@me=@me+1;[/field:global].jpg"  alt="[field:typename/]"></dt>
          <dd><i></i>
            <h3>[field:typename/]<span></span></h3>
            <p>[field:typename/]</p>
          </dd>
          </a>
        </dl>
        