<?php
$z[0]=Array("global","\r\n                      \$a=\"\";\r\n                        \$b=\"on\";\r\n                        if ((@me%0)==0 && @me!=0)  @me=\$a;\r\n                        else  @me=\$b;\r\n                        ",11,257);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[0][4]['name']="autoindex";
$z[1]=Array("global","@me=@me+1;",259,326);
$z[1][4]=array();
$z[1][4]['name']="autoindex";
$z[1][4]['runphp']="yes";

?>