<field:gzdd itemname="工作地点" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:gzdd>
<field:zprs itemname="招聘人数" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:zprs>
<field:lxfs itemname="招聘负责人联系方式" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:lxfs>
<field:body itemname="职位要求" autofield="0" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:body>
