<?php
$z[0]=Array("field","",103,132);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("field","",149,180);
$z[1][4]=array();
$z[1][4]['name']="typenameen";
$z[2]=Array("field","",223,255);
$z[2][4]=array();
$z[2][4]['name']="description";
$z[3]=Array("type","<li role=\"presentation\" class=\"active\"><a href=\"#home\" aria-controls=\"home\" role=\"tab\" data-toggle=\"tab\">[field:typename /]</a></li>",384,551);
$z[3][4]=array();
$z[3][4]['typeid']="13";
$z[4]=Array("type","<li role=\"presentation\"><a href=\"#profile\" aria-controls=\"profile\" role=\"tab\" data-toggle=\"tab\">[field:typename /]</a></li>",557,715);
$z[4][4]=array();
$z[4][4]['typeid']="14";
$z[5]=Array("field","",754,782);
$z[5][4]=array();
$z[5][4]['name']="typeurl";
$z[6]=Array("arclist","\r\n									<li><a href=\"[field:arcurl/]\"><i>[field:title/]</i><span>[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</span></a></li>\r\n									",1183,1406);
$z[6][4]=array();
$z[6][4]['typeid']="13";
$z[6][4]['row']="6";
$z[6][4]['titlelen']="50";
$z[6][4]['orderby']="pubdate";
$z[7]=Array("arclist","\r\n									<li><a href=\"[field:arcurl/]\"><i>[field:title/]</i><span>[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</span></a></li>\r\n									",1790,2013);
$z[7][4]=array();
$z[7][4]['typeid']="14";
$z[7][4]['row']="6";
$z[7][4]['titlelen']="50";
$z[7][4]['orderby']="pubdate";

?>