<li class="clearfix">
					<a href="[field:arcurl/]" class="imgs fl"><img src="[field:litpic/]" /></a>
					<div class="news_left2 fr">
					<h3><a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a></h3>
					<div>[field:description function="cn_substr(@me,300)"/]...</div>
					<span>发布时间：[field:pubdate function="MyDate('Y-m-d',@me)"/]&nbsp;&nbsp;&nbsp;点击次数：[field:click/]</span>
					</div>
				</li><hr/>