<a href="[field:arcurl/]" title="[field:title/]">
          <div class="xxxw">
            <div class="xwtp1"><img src="[field:litpic/]" alt="[field:title/]" width="210" height="158"/></div>
            <div class="xwwz1">
              <h3 >[field:title/]</h3>
              <p>[field:description function="cn_substr(@me,200)"/]...</p>
              <span>[查看详情]</span></div>
          </div>
          </a>