<?php
$z[0]=Array("field","",224,255);
$z[0][4]=array();
$z[0][4]['name']="typenameen";
$z[1]=Array("field","",402,431);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("field","",635,663);
$z[2][4]=array();
$z[2][4]['name']="typeimg";
$z[3]=Array("field","",670,699);
$z[3][4]=array();
$z[3][4]['name']="typename";
$z[4]=Array("sql"," \r\n        [field:content  function='cn_substr(html2text(@me),1200)'/]\r\n        ",769,920);
$z[4][4]=array();
$z[4][4]['sql']="Select content from dede_arctype where id=1";
$z[5]=Array("field","",974,1002);
$z[5][4]=array();
$z[5][4]['name']="typeurl";
$z[6]=Array("global","",1104,1125);
$z[6][4]=array();
$z[6][4]['name']="cfg_qq";

?>