<dl class="in_dl1">
                <dt><a href="{dede:field name=typeurl/}" title="{dede:field name=typename/}" class="img"><img src="{dede:field name=typeimg/}" alt="{dede:field name=typename/}"></a></dt>
                <dd><a href="{dede:field name=typeurl/}" title="{dede:field name=typename/}">{dede:field name=typename/}</a></dd>
                <dd>店面形象设计：公司为加盟店提供系统的装修规划及店面装修方案。<BR>
          <BR>
          培训支持：公司提供从经销商、店长、渠道业务、终端导购、设计、安装全方位系统的支持。<BR>
          <BR>
          软件支持：公司与三维家携手合作打造出了一款适合于概念的设计软件。
</dd>
			</dl>