<?php
$z[0]=Array("field","",74,103);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("field","",126,154);
$z[1][4]=array();
$z[1][4]['name']="typeurl";
$z[2]=Array("arclist","\r\n						<li>\r\n                <a href=\"[field:arcurl/]\" title=\"[field:title/]\" class=\"img\">\r\n                   <img src=\"[field:litpic/]\" alt=\"[field:title/]\" />\r\n                   <h3>[field:title/]</h3>\r\n                </a>\r\n            </li>\r\n			",224,545);
$z[2][4]=array();
$z[2][4]['row']="4";
$z[2][4]['titlelen']="50";
$z[2][4]['orderby']="pubdate";

?>