<div class="cpzx" aos="fade-up" aos-easing="ease" aos-duration="700" aos-delay="100">
  <div class="content"> 
    <!--产品分类开始-->
    <div class="nlist">
      <h4 class="nt nt1"><a href="{dede:field name='typeurl'/}" title="{dede:field name='typename'/}">{dede:field name='typename'/}</a></h4>
      <div class="TabTitle2">
        <ul class="expmenu">
          {dede:channel type='son' noself='yes'}
          <li>
            <div class="header"><a href="[field:typelink/]" title="[field:typename/]">[field:typename/]</a></div>
          </li>
          {/dede:channel}          
        </ul>
      </div>
      <!--联系方式开始-->
      <div class="contactn mt10 mb10">
        <div class="t05"> <h5><a href="/a/lianxiwomen/" title="联系我们">联系我们</a></h5> </div>
        <div class="subnr"> <img src="/skin/images/catactus.jpg"/>
          <p><b>{dede:global.cfg_gsmc/}</b> <br>
            邮箱：{dede:global.cfg_email/}<br>
            手机：{dede:global.cfg_phone/}<br>
            电话：{dede:global.cfg_tel/}<br>
            地址：{dede:global.cfg_add/}</p>
        </div>
      </div>
      <!--联系方式结束--> 
    </div>
    <!--产品分类结束-->
    <div class="cptp">
      <ul>
        <li><a href="/a/chanpin/fenlei2/25.html" title="产品中心标题五">
          <div class="pic"><img src="/uploads/allimg/190514/1-1Z5140Z5025F.jpg" alt="产品中心标题五"></div>
          <p >产品中心标题五</p>
          </a></li>
<li><a href="/a/chanpin/fenlei2/26.html" title="产品中心标题六">
          <div class="pic"><img src="/uploads/allimg/190514/1-1Z5140Z630142.jpg" alt="产品中心标题六"></div>
          <p >产品中心标题六</p>
          </a></li>
<li><a href="/a/chanpin/fenlei3/28.html" title="产品中心标题八">
          <div class="pic"><img src="/uploads/allimg/190514/1-1Z5140ZP1G2.jpg" alt="产品中心标题八"></div>
          <p >产品中心标题八</p>
          </a></li>
<li><a href="/a/chanpin/fenlei3/29.html" title="产品中心标题九">
          <div class="pic"><img src="/uploads/allimg/190514/1-1Z5140ZS9607.jpg" alt="产品中心标题九"></div>
          <p >产品中心标题九</p>
          </a></li>
<li><a href="/a/chanpin/fenlei3/27.html" title="产品中心标题七">
          <div class="pic"><img src="/uploads/allimg/190514/1-1Z5140ZH62X.jpg" alt="产品中心标题七"></div>
          <p >产品中心标题七</p>
          </a></li>
<li><a href="/a/chanpin/fenlei2/24.html" title="产品中心标题四">
          <div class="pic"><img src="/uploads/allimg/190514/1-1Z5140Z429C6.jpg" alt="产品中心标题四"></div>
          <p >产品中心标题四</p>
          </a></li>
<li><a href="/a/chanpin/fenlei1/22.html" title="产品中心标题二">
          <div class="pic"><img src="/uploads/allimg/190514/1-1Z5140Z2535U.jpg" alt="产品中心标题二"></div>
          <p >产品中心标题二</p>
          </a></li>
<li><a href="/a/chanpin/fenlei1/23.html" title="产品中心标题三">
          <div class="pic"><img src="/uploads/allimg/190514/1-1Z5140Z3325N.jpg" alt="产品中心标题三"></div>
          <p >产品中心标题三</p>
          </a></li>
<li><a href="/a/chanpin/fenlei1/21.html" title="产品中心标题一">
          <div class="pic"><img src="/uploads/allimg/190514/1-1Z5140Z113S0.jpg" alt="产品中心标题一"></div>
          <p >产品中心标题一</p>
          </a></li>

      </ul>
    </div>
  </div>
</div>