<?php
$z[0]=Array("field","",82,111);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("arclist","\r\n		<li><a href=\"view.php?aid=[field:id/]\" title=\"[field:title/]\"><img src=\"[field:litpic/]\" alt=\"[field:title/]\">\r\n          <div class=\"tl\"><em >[field:title/]</em>\r\n            <p>[field:description function=\"cn_substr(@me,200)\"/]...</p>\r\n            <i>[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</i></div>\r\n          </a></li>\r\n		  ",200,610);
$z[1][4]=array();
$z[1][4]['row']="5";
$z[1][4]['titlelen']="50";
$z[1][4]['orderby']="pubdate";
$z[2]=Array("field","",676,699);
$z[2][4]=array();
$z[2][4]['name']="id";

?>