<dd class="d[field:global runphp='yes' name=autoindex][/field:global]">
              <div class="box1"><a href="[field:arcurl/]" title="[field:title/]">
                <h3>[field:title/]</h3>
                <p>[field:description function="cn_substr(@me,155)"/]...</p>
                <i class="icon"></i><span class="icon"></span></a></div>
              <div class="box2"><a href="[field:arcurl/]" title="[field:title/]"><img src="[field:litpic/]" alt="[field:title/]"></a></div>
            </dd>