<?php
$z[0]=Array("field","",111,142);
$z[0][4]=array();
$z[0][4]['name']="typenameen";
$z[1]=Array("field","",213,242);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("channel","<a href=\"list.php?tid=[field:id/]\" title=\"[field:typename/]\">[field:typename/]</a> ",350,486);
$z[2][4]=array();
$z[2][4]['type']="son";
$z[2][4]['noself']="yes";
$z[3]=Array("arclist","\r\n		  <li><a href=\"view.php?aid=[field:id/]\" title=\"[field:title/]\">\r\n            <div class=\"img\"><img class=\"img\" src=\"[field:litpic/]\" alt=\"[field:title/]\"/></div>\r\n            <div class=\"txt\">\r\n              <h3 class=\"tit\">[field:title/]</h3>\r\n            </div>\r\n            </a></li>\r\n			",604,969);
$z[3][4]=array();
$z[3][4]['row']="6";
$z[3][4]['titlelen']="50";
$z[3][4]['orderby']="pubdate";
$z[4]=Array("field","",1046,1069);
$z[4][4]=array();
$z[4][4]['name']="id";

?>