<?php
$z[0]=Array("field","",93,122);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("field","",274,303);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("field","",366,395);
$z[2][4]=array();
$z[2][4]['name']="typename";
$z[3]=Array("sql"," \r\n        [field:content  function='cn_substr(html2text(@me),300)'/]\r\n        ",427,577);
$z[3][4]=array();
$z[3][4]['sql']="Select content from dede_arctype where id=1";
$z[4]=Array("field","",630,653);
$z[4][4]=array();
$z[4][4]['name']="id";

?>