<div class="floor_3 clearfix">
    <div class="floor_3_main w1200" >
      <div class="indexTit" aos="fade-up" aos-easing="ease" aos-duration="700" aos-delay="100">
        <h2 class="tit">{dede:field name='typename'/}</h2>
        <i></i></div>
      <div class="content" aos="fade-up" aos-easing="ease" aos-duration="700" aos-delay="200">
        <div class="case" id="case">
          <div class="bd" >
            <ul class="list clearfix">
              <li class="item"><a href="/a/anli/14.html" title="客户案例标题六"><img src="/uploads/allimg/190428/1-1Z42Q220290-L.jpg" alt="客户案例标题六"/>
                <p>客户案例标题六<i class="icon"></i></p>
                <div class="bg"></div>
                <div class="txtIco"><s class="icon"></s></div>
                </a></li>
<li class="item"><a href="/a/anli/13.html" title="客户案例标题五"><img src="/uploads/allimg/190428/1-1Z42Q220070-L.jpg" alt="客户案例标题五"/>
                <p>客户案例标题五<i class="icon"></i></p>
                <div class="bg"></div>
                <div class="txtIco"><s class="icon"></s></div>
                </a></li>
<li class="item"><a href="/a/anli/12.html" title="客户案例标题四"><img src="/uploads/allimg/190428/1-1Z42Q219470-L.jpg" alt="客户案例标题四"/>
                <p>客户案例标题四<i class="icon"></i></p>
                <div class="bg"></div>
                <div class="txtIco"><s class="icon"></s></div>
                </a></li>
<li class="item"><a href="/a/anli/11.html" title="客户案例标题三"><img src="/uploads/allimg/190428/1-1Z42Q219240-L.jpg" alt="客户案例标题三"/>
                <p>客户案例标题三<i class="icon"></i></p>
                <div class="bg"></div>
                <div class="txtIco"><s class="icon"></s></div>
                </a></li>
<li class="item"><a href="/a/anli/10.html" title="客户案例标题二"><img src="/uploads/allimg/190428/1-1Z42Q21Z30-L.jpg" alt="客户案例标题二"/>
                <p>客户案例标题二<i class="icon"></i></p>
                <div class="bg"></div>
                <div class="txtIco"><s class="icon"></s></div>
                </a></li>
<li class="item"><a href="/a/anli/9.html" title="客户案例标题一"><img src="/uploads/allimg/190428/1-1Z42Q2152N51.jpg" alt="客户案例标题一"/>
                <p>客户案例标题一<i class="icon"></i></p>
                <div class="bg"></div>
                <div class="txtIco"><s class="icon"></s></div>
                </a></li>

            </ul>
          </div>
          <div class="hd"> <span class="prev icon"></span> <a href="/a/anli/"><span class="amore icon"></span></a> <span class="next icon"></span> </div>
        </div>
      </div>
    </div>
  </div>