<?php
$z[0]=Array("field","",93,122);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("arclist","\r\n        <li><a href=\"view.php?aid=37\" title=\"[field:title/]\"><img src=\"/uploads/allimg/191029/1-191029153H80-L.jpg\" alt=\"[field:title/]\">\r\n          <div class=\"tl\"><em >[field:title/]</em>\r\n            <p>[field:description function=\"cn_substr(@me,200)\"/]...</p>\r\n            <i>[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</i></div>\r\n          </a></li>\r\n	",236,668);
$z[1][4]=array();
$z[1][4]['row']="5";
$z[1][4]['titlelen']="50";
$z[1][4]['orderby']="pubdate";
$z[2]=Array("field","",735,758);
$z[2][4]=array();
$z[2][4]['name']="id";

?>