<div class="tab">
			<div class="a1_1 fl">
				<ul class="a1_ul1">
					{dede:arclist row='4'}
					<li><a href="[field:arcurl/]" title="[field:title/]" class="img"><img src="[field:litpic/]" alt="[field:title/]"></a>
					<h3><a href="[field:arcurl/]" title="[field:title/]">[field:title/] <span></span></a></h3>
					</li>
					{/dede:arclist}
				</ul>
			</div>
			<div class="a1_2 fr">
				<p><img src="/skin/images/case.jpg" title="case.jpg" alt="case.jpg"></p>
			</div>
			<div class="clearfix"></div>
		</div>