<?php
$z[0]=Array("field","",185,214);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("field","",229,260);
$z[1][4]=array();
$z[1][4]['name']="typenameen";
$z[2]=Array("arclist","\r\n					<div class=\"col-sm-4 col-md-3 col-mm-6 product_img\">\r\n						<a href=\"[field:arcurl/]\"><img src=\"[field:litpic/]\" class=\"img-thumbnail\" alt=\"[field:title/]\"/></a>\r\n						<p class=\"product_title\">\r\n							<a href=\"[field:arcurl/]\">[field:title/]</a>\r\n						</p>\r\n					</div>\r\n					",315,680);
$z[2][4]=array();
$z[2][4]['typeid']="";
$z[2][4]['row']="4";
$z[2][4]['titlelen']="50";
$z[2][4]['orderby']="pubdate";

?>