<?php
$z[0]=Array("field","",111,142);
$z[0][4]=array();
$z[0][4]['name']="typenameen";
$z[1]=Array("field","",213,242);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("arclist","\r\n		  <li><a href=\"view.php?aid=[field:id/]\" title=\"[field:title/]\">\r\n            <div class=\"img\"><img class=\"img\" src=\"[field:litpic/]\" alt=\"[field:title/]\"/></div>\r\n            <div class=\"txt\">\r\n              <h3 class=\"tit\">[field:title/]</h3>\r\n            </div>\r\n            </a></li>\r\n			",369,744);
$z[2][4]=array();
$z[2][4]['typeid']="";
$z[2][4]['row']="6";
$z[2][4]['titlelen']="50";
$z[2][4]['orderby']="pubdate";

?>