<?php
$z[0]=Array("field","",190,219);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("field","",419,447);
$z[1][4]=array();
$z[1][4]['name']="typeimg";
$z[2]=Array("field","",454,483);
$z[2][4]=array();
$z[2][4]['name']="typename";
$z[3]=Array("sql"," \r\n        [field:content  function='cn_substr(html2text(@me),500)'/]\r\n        ",507,657);
$z[3][4]=array();
$z[3][4]['sql']="Select content from dede_arctype where id=1";
$z[4]=Array("field","",718,741);
$z[4][4]=array();
$z[4][4]['name']="id";

?>