<?php
$z[0]=Array("field","",121,150);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("channel","<a href=\"list.php?tid=[field:id/]\" title=\"[field:typename/]\">[field:typename/]</a>  ",261,398);
$z[1][4]=array();
$z[1][4]['type']="son";
$z[1][4]['noself']="yes";
$z[2]=Array("arclist","\r\n		  <li><a href=\"view.php?aid=[field:id/]\" title=\"[field:title/]\">\r\n            <figure><img src=\"[field:litpic/]\" alt=\"[field:title/]\"/></figure>\r\n            <h3 >[field:title/]</h3>\r\n            <p>[field:description function=\"cn_substr(@me,200)\"/]...</p>\r\n            <span>[查看详情]</span></a></li>\r\n			",507,901);
$z[2][4]=array();
$z[2][4]['typeid']="";
$z[2][4]['row']="5";
$z[2][4]['titlelen']="50";
$z[2][4]['orderby']="pubdate";
$z[3]=Array("field","",978,1001);
$z[3][4]=array();
$z[3][4]['name']="id";

?>