<?php
$z[0]=Array("global","",91,117);
$z[0][4]=array();
$z[0][4]['name']="cfg_powerby";
$z[1]=Array("global","",204,228);
$z[1][4]=array();
$z[1][4]['name']="cfg_beian";
$z[2]=Array("global","",230,254);
$z[2][4]=array();
$z[2][4]['name']="cfg_beian";
$z[3]=Array("global","",474,496);
$z[3][4]=array();
$z[3][4]['name']="cfg_tel";
$z[4]=Array("type","<li><a href=\"list.php?tid=[field:id /]\"><s class=\"too-map icon\"></s></a></li>",610,722);
$z[4][4]=array();
$z[4][4]['typeid']="22";
$z[5]=Array("global","",876,902);
$z[5][4]=array();
$z[5][4]['name']="cfg_webname";
$z[6]=Array("global","",1005,1030);
$z[6][4]=array();
$z[6][4]['name']="cfg_weixin";
$z[7]=Array("global","",1032,1057);
$z[7][4]=array();
$z[7][4]['name']="cfg_weixin";

?>