<?php
$z[0]=Array("flink"," [field:link /] ",178,254);
$z[0][4]=array();
$z[0][4]['titlelen']="80";
$z[0][4]['row']="24";
$z[0][4]['type']="text";
$z[1]=Array("channel","	  \r\n	  <a href=\"{dede:field name='typeurl'/}\" title=\"[field:typename/]\">[field:typename/]</a> \r\n	  	",485,635);
$z[1][4]=array();
$z[1][4]['type']="top";
$z[1][4]['row']="10";
$z[2]=Array("global","",1003,1025);
$z[2][4]=array();
$z[2][4]['name']="cfg_tel";
$z[3]=Array("global","",1149,1171);
$z[3][4]=array();
$z[3][4]['name']="cfg_add";
$z[4]=Array("global","",1398,1424);
$z[4][4]=array();
$z[4][4]['name']="cfg_powerby";
$z[5]=Array("global","",1512,1536);
$z[5][4]=array();
$z[5][4]['name']="cfg_beian";
$z[6]=Array("global","",1538,1562);
$z[6][4]=array();
$z[6][4]['name']="cfg_beian";
$z[7]=Array("global","",2004,2026);
$z[7][4]=array();
$z[7][4]['name']="cfg_tel";
$z[8]=Array("global","",2084,2105);
$z[8][4]=array();
$z[8][4]['name']="cfg_qq";
$z[9]=Array("global","",2314,2339);
$z[9][4]=array();
$z[9][4]['name']="cfg_weixin";

?>