<?php
$z[0]=Array("global","",202,224);
$z[0][4]=array();
$z[0][4]['name']="cfg_tel";
$z[1]=Array("global","",338,359);
$z[1][4]=array();
$z[1][4]['name']="cfg_qq";
$z[2]=Array("channelartlist","<li>\r\n					<h2>{dede:field name='typename'/}</h2>\r\n					<dl>\r\n						{dede:channel type='son' noself='yes'}\r\n						<dt><a href=\"[field:typelink/]\">[field:typename/]</a></dt>\r\n						{/dede:channel}						\r\n					</dl>\r\n				</li>",448,736);
$z[2][4]=array();
$z[2][4]['typeid']="1,12,15,5,0";
$z[3]=Array("global","",919,945);
$z[3][4]=array();
$z[3][4]['name']="cfg_powerby";
$z[4]=Array("global","",989,1013);
$z[4][4]=array();
$z[4][4]['name']="cfg_beian";
$z[5]=Array("global","",1055,1081);
$z[5][4]=array();
$z[5][4]['name']="cfg_powerby";
$z[6]=Array("global","",1106,1130);
$z[6][4]=array();
$z[6][4]['name']="cfg_beian";

?>