<?php
$z[0]=Array("channelartlist","<div class=\"a6_1\">\r\n			<a href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a>\r\n			{dede:channel type='son' noself='yes'}\r\n			<a href='[field:typelink/]'>[field:typename/]</a>\r\n			{/dede:channel}\r\n			\r\n		</div>",52,343);
$z[0][4]=array();
$z[0][4]['typeid']="1,12,5,22,0";
$z[1]=Array("global","",448,470);
$z[1][4]=array();
$z[1][4]['name']="cfg_add";
$z[2]=Array("global","",553,575);
$z[2][4]=array();
$z[2][4]['name']="cfg_tel";
$z[3]=Array("global","",1190,1216);
$z[3][4]=array();
$z[3][4]['name']="cfg_powerby";
$z[4]=Array("global","",1347,1371);
$z[4][4]=array();
$z[4][4]['name']="cfg_beian";
$z[5]=Array("flink","[field:link /] ",1505,1580);
$z[5][4]=array();
$z[5][4]['titlelen']="20";
$z[5][4]['row']="20";
$z[5][4]['type']="text";

?>