<?php
$z[0]=Array("global","",103,129);
$z[0][4]=array();
$z[0][4]['name']="cfg_powerby";
$z[1]=Array("global","",217,241);
$z[1][4]=array();
$z[1][4]['name']="cfg_beian";
$z[2]=Array("global","",243,267);
$z[2][4]=array();
$z[2][4]['name']="cfg_beian";
$z[3]=Array("global","",517,539);
$z[3][4]=array();
$z[3][4]['name']="cfg_tel";
$z[4]=Array("type","<li><a href=\"list.php?tid=[field:id /]\" title=\"[field:typename /]\"><s class=\"icon\"></s><span>联系我们</span></a></li>",688,844);
$z[4][4]=array();
$z[4][4]['typeid']="22";
$z[5]=Array("global","",1094,1119);
$z[5][4]=array();
$z[5][4]['name']="cfg_weixin";
$z[6]=Array("global","",1121,1146);
$z[6][4]=array();
$z[6][4]['name']="cfg_weixin";

?>