<?php
$z[0]=Array("flink","  [field:link /]<span>|</span>  ",92,184);
$z[0][4]=array();
$z[0][4]['titlelen']="20";
$z[0][4]['row']="20";
$z[0][4]['type']="text";
$z[1]=Array("channel","\r\n		  <td><a href='[field:typelink/]'>[field:typename/]</a></td>\r\n		\r\n",502,626);
$z[1][4]=array();
$z[1][4]['type']="top";
$z[1][4]['noself']="yes";
$z[2]=Array("global","",740,762);
$z[2][4]=array();
$z[2][4]['name']="cfg_tel";
$z[3]=Array("global","",798,820);
$z[3][4]=array();
$z[3][4]['name']="cfg_add";
$z[4]=Array("global","",879,905);
$z[4][4]=array();
$z[4][4]['name']="cfg_powerby";
$z[5]=Array("global","",992,1016);
$z[5][4]=array();
$z[5][4]['name']="cfg_beian";
$z[6]=Array("global","",1036,1060);
$z[6][4]=array();
$z[6][4]['name']="cfg_beian";

?>