<?php
$z[0]=Array("global","",91,117);
$z[0][4]=array();
$z[0][4]['name']="cfg_powerby";
$z[1]=Array("global","",204,228);
$z[1][4]=array();
$z[1][4]['name']="cfg_beian";
$z[2]=Array("global","",230,254);
$z[2][4]=array();
$z[2][4]['name']="cfg_beian";
$z[3]=Array("global","",493,515);
$z[3][4]=array();
$z[3][4]['name']="cfg_tel";
$z[4]=Array("type","<li><a href=\"list.php?tid=[field:id /]\"><s class=\"too-map icon\"></s><span>联系我们</span></a></li>",678,815);
$z[4][4]=array();
$z[4][4]['typeid']="14";
$z[5]=Array("global","",969,995);
$z[5][4]=array();
$z[5][4]['name']="cfg_webname";
$z[6]=Array("global","",1098,1123);
$z[6][4]=array();
$z[6][4]['name']="cfg_weixin";
$z[7]=Array("global","",1125,1150);
$z[7][4]=array();
$z[7][4]['name']="cfg_weixin";

?>