<?php
$z[0]=Array("global","",103,129);
$z[0][4]=array();
$z[0][4]['name']="cfg_powerby";
$z[1]=Array("global","",218,242);
$z[1][4]=array();
$z[1][4]['name']="cfg_beian";
$z[2]=Array("global","",244,268);
$z[2][4]=array();
$z[2][4]['name']="cfg_beian";
$z[3]=Array("global","",533,555);
$z[3][4]=array();
$z[3][4]['name']="cfg_tel";
$z[4]=Array("type","<li><a href=\"list.php?tid=[field:id /]\" title=\"[field:typename /]\"><s class=\"icon\"></s><span>[field:typename /]</span></a></li>",719,881);
$z[4][4]=array();
$z[4][4]['typeid']="14";
$z[5]=Array("global","",1131,1156);
$z[5][4]=array();
$z[5][4]['name']="cfg_weixin";
$z[6]=Array("global","",1158,1183);
$z[6][4]=array();
$z[6][4]['name']="cfg_weixin";

?>