<?php
$z[0]=Array("global","",128,154);
$z[0][4]=array();
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",195,221);
$z[1][4]=array();
$z[1][4]['name']="cfg_webname";
$z[2]=Array("channel","\r\n      <li><a href=\"[field:typelink/]\" title=\"[field:typename/]\">[field:typename/]</a></li>\r\n      ",1271,1503);
$z[2][4]=array();
$z[2][4]['type']="top";
$z[2][4]['row']="10";
$z[2][4]['currentstyle']="<li><a href='~typelink~' ~rel~>~typename~</a> </li>";

?>