<?php
$z[0]=Array("global","",118,144);
$z[0][4]=array();
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",184,210);
$z[1][4]=array();
$z[1][4]['name']="cfg_webname";
$z[2]=Array("channelartlist","\r\n            <li><a href=\"{dede:field name=typeurl/}\">{dede:field name=typename/}</a></li>\r\n			",336,486);
$z[2][4]=array();
$z[2][4]['typeid']="top";
$z[3]=Array("channelartlist","\r\n                        <ul class=\"ul\">\r\n						    {dede:channel type=son}\r\n                            <li><a href=\"[field:typeurl/]\"><span>[field:typename/]</span></a></li>\r\n							{/dede:channel}\r\n                        </ul>\r\n						",804,1097);
$z[3][4]=array();
$z[3][4]['typeid']="top";
$z[4]=Array("channelartlist","\r\n            <li><a href=\"{dede:field name=typeurl/}\">{dede:field name=typename/}</a></li>\r\n			",1519,1669);
$z[4][4]=array();
$z[4][4]['typeid']="top";

?>