<?php
$z[0]=Array("global","",91,117);
$z[0][4]=array();
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",164,189);
$z[1][4]=array();
$z[1][4]['name']="cfg_mobile";
$z[2]=Array("type","[field:typeurl/]",300,350);
$z[2][4]=array();
$z[2][4]['typeid']="6";
$z[3]=Array("global","",498,530);
$z[3][4]=array();
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",679,704);
$z[4][4]=array();
$z[4][4]['name']="cfg_mobile";
$z[5]=Array("channel","\r\n	  <li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n	  ",866,973);
$z[5][4]=array();
$z[5][4]['type']="top";
$z[6]=Array("arclist","\r\n         <li style=\"background:url([field:picname/]) center 0 no-repeat;\"><a  href=\"#\"></a></li>\r\n		",1107,1250);
$z[6][4]=array();
$z[6][4]['typeid']="37";
$z[7]=Array("arclist","\r\n        <li><img src=\"[field:picname/]\" /></li>\r\n			",1309,1404);
$z[7][4]=array();
$z[7][4]['typeid']="37";
$z[8]=Array("global","",1693,1718);
$z[8][4]=array();
$z[8][4]['name']="cfg_cmsurl";
$z[9]=Array("hotwords","",1928,1953);
$z[9][4]=array();
$z[9][4]['num']="10";

?>