<?php
$z[0]=Array("global","",670,696);
$z[0][4]=array();
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",737,763);
$z[1][4]=array();
$z[1][4]['name']="cfg_webname";
$z[2]=Array("channel","\r\n      <li><a href=\"list.php?tid=[field:id/]\" title=\"[field:typename/]\">[field:typename/]</a></li>\r\n      ",1013,1243);
$z[2][4]=array();
$z[2][4]['type']="top";
$z[2][4]['currentstyle']="<li><a href='list.php?tid=~id~'>~typename~</a></li>";

?>