<?php
$z[0]=Array("global","",104,125);
$z[0][4]=array();
$z[0][4]['name']="cfg_gg";
$z[1]=Array("type","<a href=\"[field:typelink /]\" title=\"[field:typename /]\">[field:typename /]</a>",187,300);
$z[1][4]=array();
$z[1][4]['typeid']="13";
$z[2]=Array("type"," <a href=\"[field:typelink /]\" title=\"[field:typename /]\">[field:typename /]</a>",326,440);
$z[2][4]=array();
$z[2][4]['typeid']="14";
$z[3]=Array("global","",642,668);
$z[3][4]=array();
$z[3][4]['name']="cfg_webname";
$z[4]=Array("global","",766,792);
$z[4][4]=array();
$z[4][4]['name']="cfg_webname";
$z[5]=Array("global","",950,972);
$z[5][4]=array();
$z[5][4]['name']="cfg_tel";
$z[6]=Array("field","(@me==\"\")? @me=\" class='hover'\":@me=\"\";",1177,1266);
$z[6][4]=array();
$z[6][4]['name']="typeid";
$z[6][4]['runphp']="yes";
$z[7]=Array("channelartlist","\r\n		<li class=\"item\">\r\n		<a class=\"hvr-underline-from-center1 \" class=\"{dede:field.currentstyle/}\" href=\"{dede:field name='typeurl'/}\" title=\"{dede:field name='typename'/}\">\r\n		{dede:field name='typename'/}\r\n		</a>\r\n         <div class=\"suNav\">  \r\n		  {dede:channel type='son' noself='yes'}\r\n		   <a class=\"subA\" href=\"[field:typelink/]\" title=\"[field:typename/]\">[field:typename/]</a> \r\n		  {/dede:channel} \r\n		 </div>\r\n        </li>\r\n		",1333,1856);
$z[7][4]=array();
$z[7][4]['row']="7";
$z[7][4]['typeid']="top";
$z[7][4]['currentstyle']="hover";

?>