<?php
$z[0]=Array("global","",36,58);
$z[0][4]=array();
$z[0][4]['name']="cfg_top";
$z[1]=Array("global","",165,191);
$z[1][4]=array();
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",234,260);
$z[2][4]=array();
$z[2][4]['name']="cfg_webname";
$z[3]=Array("global","",374,396);
$z[3][4]=array();
$z[3][4]['name']="cfg_tel";
$z[4]=Array("channelartlist","  \r\n				  <td  class=\"\">\r\n<a class=\"{dede:field.currentstyle/}\" href=\"{dede:field name='typeurl'/}\" title=\"{dede:field name='typename'/}\">{dede:field name='typename'/}<br /><!-- <span></span> --><div></div></a>\r\n                        <div class=\"nav_tan\">\r\n						\r\n                {dede:channel type='son' noself='yes' }\r\n<li><a href='[field:typelink/]'>[field:typename/]</a></li>\r\n{/dede:channel}\r\n				\r\n				\r\n				          </div>  \r\n				</td>\r\n				\r\n				",775,1319);
$z[4][4]=array();
$z[4][4]['typeid']="1,2,3,4,5,6,7";
$z[4][4]['currentstyle']="now";
$z[5]=Array("field","(@me==\"\")? @me=\" class='current'\":@me=\"\";",1340,1431);
$z[5][4]=array();
$z[5][4]['name']="typeid";
$z[5][4]['runphp']="yes";

?>