<?php
$z[0]=Array("global","",128,154);
$z[0][4]=array();
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",198,224);
$z[1][4]=array();
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",428,453);
$z[2][4]=array();
$z[2][4]['name']="cfg_cmsurl";
$z[3]=Array("channel","\r\n      <li><a href=\"list.php?tid=[field:id/]\" title=\"[field:typename/]\">[field:typename/]</a></li>\r\n      ",1287,1517);
$z[3][4]=array();
$z[3][4]['type']="top";
$z[3][4]['currentstyle']="<li><a href='list.php?tid=~id~'>~typename~</a></li>";

?>