<?php
$z[0]=Array("global","",99,120);
$z[0][4]=array();
$z[0][4]['name']="cfg_gg";
$z[1]=Array("type","<li><a href=\"[field:typelink /]\" title=\"[field:typename /]\">[field:typename /]</a></li>",346,468);
$z[1][4]=array();
$z[1][4]['typeid']="22";
$z[2]=Array("global","",695,721);
$z[2][4]=array();
$z[2][4]['name']="cfg_webname";
$z[3]=Array("global","",761,787);
$z[3][4]=array();
$z[3][4]['name']="cfg_webname";
$z[4]=Array("global","",970,992);
$z[4][4]=array();
$z[4][4]['name']="cfg_tel";
$z[5]=Array("field","(@me==\"\")? @me=\" class='hover' \":@me=\"\";",1291,1381);
$z[5][4]=array();
$z[5][4]['name']="typeid";
$z[5][4]['runphp']="yes";
$z[6]=Array("channelartlist","<li class='{dede:field.currentstyle/}'><a class=\"aLink\" href=\"{dede:field name='typeurl'/}\" title=\"{dede:field name='typename'/}\">{dede:field name='typename'/}<i></i></a>\r\n          <ul class=\"subnav\">\r\n            {dede:channel type='son' noself='yes'}\r\n            <li class=\"nav1\"><a href=\"[field:typelink/]\" title=\"[field:typename/]\">[field:typename/]</a></li>\r\n            {/dede:channel}\r\n          </ul>\r\n        </li>",1446,1956);
$z[6][4]=array();
$z[6][4]['row']="8";
$z[6][4]['typeid']="top";
$z[6][4]['currentstyle']="hover";

?>