<?php
$z[0]=Array("global","",104,125);
$z[0][4]=array();
$z[0][4]['name']="cfg_gg";
$z[1]=Array("type","<li><a href=\"[field:typelink /]\" title=\"[field:typename /]\">[field:typename /]</a></li>",382,504);
$z[1][4]=array();
$z[1][4]['typeid']="14";
$z[2]=Array("global","",661,687);
$z[2][4]=array();
$z[2][4]['name']="cfg_webname";
$z[3]=Array("global","",794,820);
$z[3][4]=array();
$z[3][4]['name']="cfg_webname";
$z[4]=Array("global","",969,991);
$z[4][4]=array();
$z[4][4]['name']="cfg_tel";
$z[5]=Array("field","(@me==\"\")? @me=\" class='hover'\":@me=\"\";",1137,1226);
$z[5][4]=array();
$z[5][4]['name']="typeid";
$z[5][4]['runphp']="yes";
$z[6]=Array("channelartlist","<li class=\"{dede:field.currentstyle/}\"><a class=\"aLink\" href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a>\r\n      <ul class=\"subnav\">\r\n        {dede:channel type='son' noself='yes'}\r\n        <li class=\"nav1\"><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n        {/dede:channel}        \r\n      </ul>\r\n    </li>",1280,1703);
$z[6][4]=array();
$z[6][4]['row']="7";
$z[6][4]['typeid']="top";
$z[6][4]['currentstyle']="hover";

?>