<?php
$z[0]=Array("channelartlist","\r\n				<li><a href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a>\r\n				<ul>\r\n				{dede:channel type='son' noself='yes'}\r\n							<li>\r\n								<a href=\"[field:typeurl/]\">[field:typename/]</a>\r\n							</li>\r\n				{/dede:channel}			\r\n					 </ul>\r\n					 </li>\r\n				",272,611);
$z[0][4]=array();
$z[0][4]['typeid']="7,8,9,10";
$z[1]=Array("channelartlist","\r\n				<li><a href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a>\r\n					 </li>\r\n				",619,785);
$z[1][4]=array();
$z[1][4]['typeid']="11,12,13,14";
$z[2]=Array("global","",1045,1071);
$z[2][4]=array();
$z[2][4]['name']="cfg_webname";
$z[3]=Array("global","",1097,1119);
$z[3][4]=array();
$z[3][4]['name']="cfg_lxr";
$z[4]=Array("global","",1143,1168);
$z[4][4]=array();
$z[4][4]['name']="cfg_mobile";
$z[5]=Array("global","",1191,1218);
$z[5][4]=array();
$z[5][4]['name']="cfg_youxiang";
$z[6]=Array("global","",1247,1274);
$z[6][4]=array();
$z[6][4]['name']="cfg_basehost";
$z[7]=Array("global","",1409,1433);
$z[7][4]=array();
$z[7][4]['name']="cfg_dizhi";

?>