<?php
$z[0]=Array("global","",134,161);
$z[0][4]=array();
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",170,196);
$z[1][4]=array();
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",236,262);
$z[2][4]=array();
$z[2][4]['name']="cfg_webname";
$z[3]=Array("global","",365,387);
$z[3][4]=array();
$z[3][4]['name']="cfg_tel";
$z[4]=Array("field","if(@me == \"\") @me = \"class='on'\";else @me = \"\";",458,557);
$z[4][4]=array();
$z[4][4]['name']="typeid";
$z[4][4]['runphp']="yes";
$z[5]=Array("channelartlist","\r\n        <li {dede:field name=currentstyle/} > <a href=\"{dede:field name=typeurl/}\" target=\"_self\"  class=\"v1\" >{dede:field name=typename/}</a>\r\n          <dl>\r\n		    {dede:channel type=son}\r\n            <dd><a href=\"[field:typeurl/]\">[field:typename/]</a></dd>\r\n			{/dede:channel}\r\n          </dl>\r\n        </li>\r\n	    ",591,966);
$z[5][4]=array();
$z[5][4]['typeid']="top";

?>