<?php
$z[0]=Array("global","",21,47);
$z[0][4]=array();
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",188,213);
$z[1][4]=array();
$z[1][4]['name']="cfg_cmsurl";
$z[2]=Array("global","",558,590);
$z[2][4]=array();
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",636,668);
$z[3][4]=array();
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",714,746);
$z[4][4]=array();
$z[4][4]['name']="cfg_templets_skin";

?>