<?php
$z[0]=Array("global","",117,143);
$z[0][4]=array();
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",328,350);
$z[1][4]=array();
$z[1][4]['name']="cfg_tel";
$z[2]=Array("field","(@me==\"\")? @me=\"class='currt'\":@me=\"\";",468,556);
$z[2][4]=array();
$z[2][4]['name']="typeid";
$z[2][4]['runphp']="yes";
$z[3]=Array("channel","\r\n				<li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n				",587,797);
$z[3][4]=array();
$z[3][4]['type']="top";
$z[3][4]['row']="7";
$z[3][4]['currentstyle']="<li><a class='currt' href='~typelink~' ~rel~>~typename~</a></li>";

?>