<?php
$z[0]=Array("global","",156,177);
$z[0][4]=array();
$z[0][4]['name']="cfg_gg";
$z[1]=Array("global","",253,279);
$z[1][4]=array();
$z[1][4]['name']="cfg_webname";
$z[2]=Array("type","<li><a href=\"[field:typelink /]\" title=\"[field:typename /]\">[field:typename /]</a></li>",367,489);
$z[2][4]=array();
$z[2][4]['typeid']="21";
$z[3]=Array("global","",750,776);
$z[3][4]=array();
$z[3][4]['name']="cfg_webname";
$z[4]=Array("global","",905,931);
$z[4][4]=array();
$z[4][4]['name']="cfg_webname";
$z[5]=Array("global","",1082,1104);
$z[5][4]=array();
$z[5][4]['name']="cfg_tel";
$z[6]=Array("field","(@me==\"\")? @me=\" class='hover' \":@me=\"\";",1335,1425);
$z[6][4]=array();
$z[6][4]['name']="typeid";
$z[6][4]['runphp']="yes";
$z[7]=Array("channelartlist","<li class='{dede:field.currentstyle/}'><a href=\"{dede:field name='typeurl'/}\" title=\"{dede:field name='typename'/}\">{dede:field name='typename'/}</a>\r\n        <dl>\r\n          {dede:channel type='son' noself='yes'}\r\n          <dd><a href=\"[field:typelink/]\" title=\"[field:typename/]\">[field:typename/]</a></dd>\r\n          {/dede:channel}          \r\n        </dl>\r\n      </li>",1467,1926);
$z[7][4]=array();
$z[7][4]['row']="8";
$z[7][4]['typeid']="top";
$z[7][4]['currentstyle']="hover";

?>