<?php
$z[0]=Array("global","",79,100);
$z[0][4]=array();
$z[0][4]['name']="cfg_gg";
$z[1]=Array("type","<li><a href=\"[field:typelink /]\" title=\"[field:typename /]\">[field:typename /]</a></li>",142,264);
$z[1][4]=array();
$z[1][4]['typeid']="13";
$z[2]=Array("type","<li><a href=\"[field:typelink /]\" title=\"[field:typename /]\">[field:typename /]</a></li>",273,395);
$z[2][4]=array();
$z[2][4]['typeid']="14";
$z[3]=Array("global","",758,784);
$z[3][4]=array();
$z[3][4]['name']="cfg_webname";
$z[4]=Array("global","",824,850);
$z[4][4]=array();
$z[4][4]['name']="cfg_webname";
$z[5]=Array("global","",1229,1251);
$z[5][4]=array();
$z[5][4]['name']="cfg_tel";
$z[6]=Array("field","(@me==\"\")? @me=\" class='cur' \":@me=\"\";",1408,1496);
$z[6][4]=array();
$z[6][4]['name']="typeid";
$z[6][4]['runphp']="yes";
$z[7]=Array("channelartlist","<li class=\"{dede:field.currentstyle/}\"><a href=\"{dede:field name='typeurl'/}\" title=\"{dede:field name='typename'/}\">{dede:field name='typename'/}</a>\r\n      <div class=\"ej_Nav\">\r\n        <dd>{dede:channel type='son' noself='yes'}  <a href=\"[field:typelink/]\" title=\"[field:typename/]\">[field:typename/]</a>{/dede:channel} </dd>\r\n      </div>\r\n    </li>",1557,1992);
$z[7][4]=array();
$z[7][4]['row']="8";
$z[7][4]['typeid']="top";
$z[7][4]['currentstyle']="cur";

?>