<?php
$z[0]=Array("include","",1380,1419);
$z[0][4]=array();
$z[0][4]['filename']="header_m.htm";
$z[1]=Array("field","",1525,1554);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("channel","\r\n				  <li><a href=\"list.php?tid=[field:id/]\">[field:typename/]</a></li>\r\n				  ",1595,1732);
$z[2][4]=array();
$z[2][4]['type']="son";
$z[2][4]['currentstyle']="";
$z[3]=Array("include","",1853,1892);
$z[3][4]=array();
$z[3][4]['filename']="footer_m.htm";

?>