<?php
$z[0]=Array("arclist","\r\n			<li><a href=\"[field:arcurl/]\" title=\"[field:title/]\"><img src=\"[field:litpic/]\" alt=\"[field:title/]\">\r\n              <p>[field:title/]</p>\r\n              </a></li>\r\n			  ",183,446);
$z[0][4]=array();
$z[0][4]['typeid']="5";
$z[0][4]['row']="4";
$z[0][4]['flag']="";
$z[0][4]['titlelen']="50";
$z[0][4]['orderby']="pubdate";
$z[1]=Array("global","",692,718);
$z[1][4]=array();
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",750,774);
$z[2][4]=array();
$z[2][4]['name']="cfg_email";
$z[3]=Array("global","",804,828);
$z[3][4]=array();
$z[3][4]['name']="cfg_phone";
$z[4]=Array("global","",858,880);
$z[4][4]=array();
$z[4][4]['name']="cfg_tel";
$z[5]=Array("global","",910,932);
$z[5][4]=array();
$z[5][4]['name']="cfg_add";

?>