<?php
$z[0]=Array("field","",821,879);
$z[0][4]=array();
$z[0][4]['name']="typeid";
$z[0][4]['function']="GetTopTypename(@me)";
$z[1]=Array("channel","\r\n			<li><a indepth=\"true\" href=\"[field:typelink/]\">[field:typename/]</a><i></i></li>\r\n			",940,1178);
$z[1][4]=array();
$z[1][4]['type']="son";
$z[1][4]['currentstyle']="<li class='current'><a indepth='true' href='~typelink~'>~typename~</a><i></i></li>";
$z[2]=Array("global","",2222,2244);
$z[2][4]=array();
$z[2][4]['name']="cfg_lxr";
$z[3]=Array("global","",2264,2288);
$z[3][4]=array();
$z[3][4]['name']="cfg_phone";
$z[4]=Array("global","",2308,2330);
$z[4][4]=array();
$z[4][4]['name']="cfg_tel";
$z[5]=Array("global","",2350,2374);
$z[5][4]=array();
$z[5][4]['name']="cfg_email";
$z[6]=Array("global","",2394,2416);
$z[6][4]=array();
$z[6][4]['name']="cfg_add";

?>