<?php
$z[0]=Array("field","",51,105);
$z[0][4]=array();
$z[0][4]['name']="typeid";
$z[0][4]['function']="getToptype(@me,typename)";
$z[1]=Array("channel","\r\n          <h3 ><a href=\"[field:typeurl/]\">[field:typename/]</a><span></span></h3>\r\n		  ",171,382);
$z[1][4]=array();
$z[1][4]['type']="son";
$z[1][4]['currentstyle']="<h3 class='on'><a href='~typelink~'>~typename~</a><span></span></h3>";
$z[2]=Array("arclist","\r\n          <li><a href=\"[field:arcurl/]\"  title=\"[field:fulltitle/]\">[field:title/]</a></li>\r\n		  ",893,1049);
$z[2][4]=array();
$z[2][4]['row']="4";
$z[2][4]['typeid']="9";
$z[2][4]['titlelen']="100";
$z[3]=Array("global","",1178,1203);
$z[3][4]=array();
$z[3][4]['name']="cfg_person";
$z[4]=Array("global","",1233,1255);
$z[4][4]=array();
$z[4][4]['name']="cfg_tel";
$z[5]=Array("global","",1285,1309);
$z[5][4]=array();
$z[5][4]['name']="cfg_phone";
$z[6]=Array("global","",1339,1363);
$z[6][4]=array();
$z[6][4]['name']="cfg_email";
$z[7]=Array("global","",1393,1415);
$z[7][4]=array();
$z[7][4]['name']="cfg_add";

?>