<?php
$z[0]=Array("field","",85,143);
$z[0][4]=array();
$z[0][4]['name']="typeid";
$z[0][4]['function']="GetTopTypename(@me)";
$z[1]=Array("channel","<li><a class=\"biglink \" href=\"[field:typelink/]\">[field:typename/]</a></li>",231,427);
$z[1][4]=array();
$z[1][4]['type']="son";
$z[1][4]['currentstyle']="<li><a class='biglink curr' href='~typelink~'>~typename~</a></li>";
$z[2]=Array("arclist","\r\n			<li><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a><span class=\"news_time\">[field:pubdate function=\"MyDate('m/d',@me)\"/]</span></li>\r\n			",558,801);
$z[2][4]=array();
$z[2][4]['typeid']="12";
$z[2][4]['row']="5";
$z[2][4]['titlelen']="40";
$z[2][4]['orderby']="pubdate";
$z[3]=Array("global","",950,972);
$z[3][4]=array();
$z[3][4]['name']="cfg_lxr";
$z[4]=Array("global","",992,1016);
$z[4][4]=array();
$z[4][4]['name']="cfg_phone";
$z[5]=Array("global","",1036,1058);
$z[5][4]=array();
$z[5][4]['name']="cfg_tel";
$z[6]=Array("global","",1078,1102);
$z[6][4]=array();
$z[6][4]['name']="cfg_email";
$z[7]=Array("global","",1123,1145);
$z[7][4]=array();
$z[7][4]['name']="cfg_add";

?>