<?php
$z[0]=Array("channelartlist","<li><a class=\"li1\" href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a>\r\n					<ul class='ul2 reset'>\r\n						{dede:channel type='son' noself='yes'}\r\n						<li><a href=\"[field:typelink/]\" target=\"_top\"><i class=\"fa fa-angle-right\"></i>[field:typename/]</a></li>\r\n						{/dede:channel}						\r\n					</ul>\r\n					</li>",1021,1415);
$z[0][4]=array();
$z[0][4]['typeid']="5";
$z[0][4]['type']="son";
$z[1]=Array("global","",2543,2565);
$z[1][4]=array();
$z[1][4]['name']="cfg_lxr";
$z[2]=Array("global","",2585,2609);
$z[2][4]=array();
$z[2][4]['name']="cfg_phone";
$z[3]=Array("global","",2629,2651);
$z[3][4]=array();
$z[3][4]['name']="cfg_tel";
$z[4]=Array("global","",2671,2695);
$z[4][4]=array();
$z[4][4]['name']="cfg_email";
$z[5]=Array("global","",2715,2737);
$z[5][4]=array();
$z[5][4]['name']="cfg_add";

?>