<?php
$z[0]=Array("field","",130,188);
$z[0][4]=array();
$z[0][4]['name']="typeid";
$z[0][4]['function']="GetTopTypename(@me)";
$z[1]=Array("channel","\r\n			<li><a href=\"[field:typelink/]\" title=\"[field:typename/]\">[field:typename/]</a> </li>\r\n			",267,486);
$z[1][4]=array();
$z[1][4]['type']="son";
$z[1][4]['currentstyle']="<li class='hover'><a href='~typelink~'>~typename~</a></li>";
$z[2]=Array("arclist","\r\n			<li><a href=\"[field:arcurl/]\" title=\"[field:title/]\"><img src=\"[field:litpic/]\" alt=\"[field:title/]\">\r\n              <p>[field:title/]</p>\r\n              </a></li>\r\n			  ",770,1033);
$z[2][4]=array();
$z[2][4]['typeid']="5";
$z[2][4]['row']="4";
$z[2][4]['flag']="";
$z[2][4]['titlelen']="50";
$z[2][4]['orderby']="pubdate";
$z[3]=Array("global","",1279,1305);
$z[3][4]=array();
$z[3][4]['name']="cfg_webname";
$z[4]=Array("global","",1337,1361);
$z[4][4]=array();
$z[4][4]['name']="cfg_email";
$z[5]=Array("global","",1391,1415);
$z[5][4]=array();
$z[5][4]['name']="cfg_phone";
$z[6]=Array("global","",1445,1467);
$z[6][4]=array();
$z[6][4]['name']="cfg_tel";
$z[7]=Array("global","",1497,1519);
$z[7][4]=array();
$z[7][4]['name']="cfg_add";

?>