<?php
$z[0]=Array("field","",90,148);
$z[0][4]=array();
$z[0][4]['name']="typeid";
$z[0][4]['function']="GetTopTypename(@me)";
$z[1]=Array("field","",150,208);
$z[1][4]=array();
$z[1][4]['name']="typeid";
$z[1][4]['function']="GetTopTypename(@me)";
$z[2]=Array("channel","\r\n      <li>\r\n        <div class=\"header\"><a href=\"[field:typelink/]\" title=\"[field:typename/]\">[field:typename/]</a></div>\r\n      </li>\r\n		",278,566);
$z[2][4]=array();
$z[2][4]['type']="son";
$z[2][4]['currentstyle']="<li class='on'> <div class='header'><a href='~typelink~'>~typename~</a></div> </li>";
$z[3]=Array("arclist","\r\n	  <li><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a></li>\r\n	  ",756,922);
$z[3][4]=array();
$z[3][4]['typeid']="9";
$z[3][4]['row']="6";
$z[3][4]['titlelen']="50";
$z[3][4]['orderby']="pubdate";
$z[4]=Array("type","<a href=\"[field:typelink /]\" title=\"[field:typename /]\">[field:typename /]</a>",1075,1188);
$z[4][4]=array();
$z[4][4]['typeid']="14";
$z[5]=Array("global","",1329,1353);
$z[5][4]=array();
$z[5][4]['name']="cfg_email";
$z[6]=Array("global","",1376,1400);
$z[6][4]=array();
$z[6][4]['name']="cfg_phone";
$z[7]=Array("global","",1423,1445);
$z[7][4]=array();
$z[7][4]['name']="cfg_tel";
$z[8]=Array("global","",1468,1490);
$z[8][4]=array();
$z[8][4]['name']="cfg_add";

?>