<?php
$z[0]=Array("field","",47,105);
$z[0][4]=array();
$z[0][4]['name']="typeid";
$z[0][4]['function']="GetTopTypename(@me)";
$z[1]=Array("channel","\r\n		<h4><span class=\"iconfont icon-jiantou\"></span><a href='[field:typelink/]'>[field:typename/]</a><span></span></h4>\r\n		",162,459);
$z[1][4]=array();
$z[1][4]['type']="son";
$z[1][4]['currentstyle']="<h4 class='on'><span class='iconfont icon-jiantou'></span><a href='~typelink~'>~typename~</a><span></span></h4>";
$z[2]=Array("arclist","\r\n		<li><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a></li>\r\n		",894,1058);
$z[2][4]=array();
$z[2][4]['typeid']="3";
$z[2][4]['row']="5";
$z[2][4]['titlelen']="50";
$z[2][4]['orderby']="pubdate";
$z[3]=Array("global","",1151,1173);
$z[3][4]=array();
$z[3][4]['name']="cfg_tel";
$z[4]=Array("global","",1193,1217);
$z[4][4]=array();
$z[4][4]['name']="cfg_phone";
$z[5]=Array("global","",1237,1261);
$z[5][4]=array();
$z[5][4]['name']="cfg_email";
$z[6]=Array("global","",1281,1303);
$z[6][4]=array();
$z[6][4]['name']="cfg_add";

?>