<?php
$z[0]=Array("field","",449,468);
$z[0][4]=array();
$z[0][4]['name']="title";
$z[1]=Array("global","",469,495);
$z[1][4]=array();
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",536,565);
$z[2][4]=array();
$z[2][4]['name']="keywords";
$z[3]=Array("field","",605,663);
$z[3][4]=array();
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1347,1386);
$z[4][4]=array();
$z[4][4]['filename']="header_m.htm";
$z[5]=Array("list","\r\n				<li>\r\n            <a href=\"view.php?aid=[field:id/]\" title=\"[field:title/]\">\r\n                <img src=\"[field:litpic/]\" alt=\"[field:title/]\">\r\n            </a>\r\n        </li>\r\n		",1544,1766);
$z[5][4]=array();
$z[5][4]['pagesize']="6";
$z[6]=Array("pagelist","",1811,1867);
$z[6][4]=array();
$z[6][4]['listitem']="pre,next,pageno";
$z[6][4]['listsize']="5";
$z[7]=Array("channel","\r\n		 <li class=\"yiji clearfix\">\r\n      <a href=\"view.php?aid=[field:id/]\" class=\"list_item\">[field:typename/]</a>\r\n      <span class=\"class-down\"></span>\r\n      <div class=\"layer2\" style=\"display:none;\">\r\n        <ul>\r\n                    </ul>\r\n      </div>\r\n    </li>\r\n	",1944,2272);
$z[7][4]=array();
$z[7][4]['type']="son";
$z[7][4]['currentstyle']="";
$z[8]=Array("include","",2418,2457);
$z[8][4]=array();
$z[8][4]['filename']="footer_m.htm";

?>