<?php
$z[0]=Array("field","",254,276);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("global","",277,303);
$z[1][4]=array();
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",344,373);
$z[2][4]=array();
$z[2][4]['name']="keywords";
$z[3]=Array("field","",413,471);
$z[3][4]=array();
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1476,1511);
$z[4][4]=array();
$z[4][4]['filename']="head.htm";
$z[5]=Array("include","",1537,1571);
$z[5][4]=array();
$z[5][4]['filename']="ban.htm";
$z[6]=Array("channel","\r\n            <li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n			",1672,1861);
$z[6][4]=array();
$z[6][4]['type']="son";
$z[6][4]['currentstyle']="<li class='navon1'><a href='~typelink~'>~typename~</a></li>";
$z[7]=Array("field","",2036,2063);
$z[7][4]=array();
$z[7][4]['name']="position";
$z[8]=Array("list","\r\n            <div class=\"ny_news_list anim anim-1\"><a href=\"[field:arcurl/]\" title=\"[field:fulltitle/]\">\r\n                <div class=\"n_news_l\">\r\n                    <div class=\"img\"><img src=\"[field:litpic/]\" alt=\"[field:fulltitle/]\"></div>\r\n                </div>\r\n                <div class=\"n_news_r\">\r\n                    <h3>[field:title/]</h3>\r\n                    <span>[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</span>\r\n                    <p>[field:description/]...</p>\r\n                </div>\r\n                </a></div>\r\n			",2184,2760);
$z[8][4]=array();
$z[8][4]['pagesize']="8";
$z[9]=Array("pagelist","",2890,2961);
$z[9][4]=array();
$z[9][4]['listitem']="info,index,end,pre,next,pageno";
$z[9][4]['listsize']="3";
$z[10]=Array("include","",2993,3030);
$z[10][4]=array();
$z[10][4]['filename']="footer.htm";

?>