<?php
$z[0]=Array("global","",264,290);
$z[0][4]=array();
$z[0][4]['name']="cfg_webname";
$z[1]=Array("include","",743,778);
$z[1][4]=array();
$z[1][4]['filename']="head.htm";
$z[2]=Array("global","",1101,1156);
$z[2][4]=array();
$z[2][4]['name']="keyword";
$z[2][4]['function']="RemoveXSS(@me)";
$z[3]=Array("channel","\r\n			<li><a href=\"[field:typelink/]\" title=\"[field:typename/]\">[field:typename/]</a> </li>\r\n			",1408,1627);
$z[3][4]=array();
$z[3][4]['type']="top";
$z[3][4]['currentstyle']="<li class='hover'><a href='~typelink~'>~typename~</a></li>";
$z[4]=Array("include","",1728,1764);
$z[4][4]=array();
$z[4][4]['filename']="left2.htm";
$z[5]=Array("list","<li class=\"item\"><a class=\"clearfix\" href=\"[field:arcurl/]\" title=\"[field:title/]\">\r\n            <div class=\"txt fr\">\r\n              <h3>[field:title/]</h3>\r\n              <div class=\"mark\"><span>时间：[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</span><span>浏览量：[field:click/]</span></div>\r\n              <p class=\"desc\">[field:description function=\"cn_substr(@me,200)\"/]...</p>\r\n            </div>\r\n            <div class=\"img\"><img src=\"[field:litpic/]\" alt=\"[field:title/]\"></div>\r\n            </a></li>",1920,2478);
$z[5][4]=array();
$z[5][4]['pagesize']="5";
$z[6]=Array("pagelist","",2587,2653);
$z[6][4]=array();
$z[6][4]['listitem']="index,end,pre,next,pageno";
$z[6][4]['listsize']="1";
$z[7]=Array("include","",2741,2778);
$z[7][4]=array();
$z[7][4]['filename']="footer.htm";

?>