<?php
$z[0]=Array("global","",254,280);
$z[0][4]=array();
$z[0][4]['name']="cfg_webname";
$z[1]=Array("include","",799,834);
$z[1][4]=array();
$z[1][4]['filename']="head.htm";
$z[2]=Array("channelartlist","<dl class=\"sitemap\">\r\n          <dt><a href=\"{dede:field name='typeurl'/}\" title=\"{dede:field name='typename'/}\">{dede:field name='typename'/}</a></dt>\r\n          <dd>  {dede:channel type='son' noself='yes'}<a href=\"[field:typelink/]\" title=\"[field:typename/]\">[field:typename/]</a>  {/dede:channel}</dd>\r\n        </dl>",1766,2168);
$z[2][4]=array();
$z[2][4]['row']="8";
$z[2][4]['typeid']="top";
$z[2][4]['currentstyle']="cur";
$z[3]=Array("include","",2251,2288);
$z[3][4]=array();
$z[3][4]['filename']="footer.htm";

?>