<?php
$z[0]=Array("global","",254,280);
$z[0][4]=array();
$z[0][4]['name']="cfg_webname";
$z[1]=Array("include","",746,781);
$z[1][4]=array();
$z[1][4]['filename']="head.htm";
$z[2]=Array("channel","\r\n			<li><a href=\"[field:typelink/]\" title=\"[field:typename/]\">[field:typename/]</a> </li>\r\n			",1393,1623);
$z[2][4]=array();
$z[2][4]['type']="son";
$z[2][4]['typeid']="5";
$z[2][4]['currentstyle']="<li class='hover'><a href='~typelink~'>~typename~</a></li>";
$z[3]=Array("include","",1724,1760);
$z[3][4]=array();
$z[3][4]['filename']="left2.htm";
$z[4]=Array("channelartlist","<dl class=\"sitemap\">\r\n          <dt><a href=\"{dede:field name='typeurl'/}\" title=\"{dede:field name='typename'/}\">{dede:field name='typename'/}</a></dt>\r\n          <dd>  {dede:channel type='son' noself='yes'}<a href=\"[field:typelink/]\" title=\"[field:typename/]\">[field:typename/]</a>  {/dede:channel}</dd>\r\n        </dl>",1881,2275);
$z[4][4]=array();
$z[4][4]['typeid']="top";
$z[4][4]['currentstyle']="cur";
$z[5]=Array("include","",2368,2405);
$z[5][4]=array();
$z[5][4]['filename']="footer.htm";

?>