<?php  exit();
/*
Page: /admin/ppt_main.php
Error: Table 't180.dede_myppt' doesn't exist <br />Error sql: <font color='red'>SELECT COUNT(*) AS dd FROM `dede_myppt` LIMIT 0,1;</font>
Time2019-01-08 09:57:52
*/
?>
<?php  exit();
/*
Page: /admin/ppt_main.php
Error: Table 't180.dede_myppt' doesn't exist <br />Error sql: <font color='red'>Select * from `dede_myppt`  order by aid desc,orderid asc LIMIT 0,20</font>
Time2019-01-08 09:57:52
*/
?>
<?php  exit();
/*
Page: /admin/ppt_main.php
Error: Table 't180.dede_myppt' doesn't exist <br />Error sql: <font color='red'>SELECT COUNT(*) AS dd FROM `dede_myppt` LIMIT 0,1;</font>
Time2019-01-08 09:57:56
*/
?>
<?php  exit();
/*
Page: /admin/ppt_main.php
Error: Table 't180.dede_myppt' doesn't exist <br />Error sql: <font color='red'>Select * from `dede_myppt`  order by aid desc,orderid asc LIMIT 0,20</font>
Time2019-01-08 09:57:56
*/
?>
<?php  exit();
/*
Page: /admin/ppt_add.php
Error: Table 't180.dede_myppttype' doesn't exist <br />Error sql: <font color='red'>SELECT * FROM `dede_myppttype` ORDER BY id DESC</font>
Time2019-01-08 09:57:58
*/
?>
<?php  exit();
/*
Page: /admin/ppt_main.php
Error: Table 't180.dede_myppt' doesn't exist <br />Error sql: <font color='red'>SELECT COUNT(*) AS dd FROM `dede_myppt` LIMIT 0,1;</font>
Time2019-01-08 10:00:26
*/
?>
<?php  exit();
/*
Page: /admin/ppt_main.php
Error: Table 't180.dede_myppt' doesn't exist <br />Error sql: <font color='red'>Select * from `dede_myppt`  order by aid desc,orderid asc LIMIT 0,20</font>
Time2019-01-08 10:00:26
*/
?>
<?php  exit();
/*
Page: /admin/ppt_add.php
Error: Table 't180.dede_myppttype' doesn't exist <br />Error sql: <font color='red'>SELECT * FROM `dede_myppttype` ORDER BY id DESC</font>
Time2019-01-08 10:00:33
*/
?>
<?php  exit();
/*
Page: /admin/ppt_main.php
Error: Table 't180.dede_myppt' doesn't exist <br />Error sql: <font color='red'>SELECT COUNT(*) AS dd FROM `dede_myppt` LIMIT 0,1;</font>
Time2019-01-08 10:00:49
*/
?>
<?php  exit();
/*
Page: /admin/ppt_main.php
Error: Table 't180.dede_myppt' doesn't exist <br />Error sql: <font color='red'>Select * from `dede_myppt`  order by aid desc,orderid asc LIMIT 0,20</font>
Time2019-01-08 10:00:49
*/
?>
<?php  exit();
/*
Page: /admin/ppt_add.php
Error: Table 't180.dede_myppttype' doesn't exist <br />Error sql: <font color='red'>SELECT * FROM `dede_myppttype` ORDER BY id DESC</font>
Time2019-01-08 10:00:51
*/
?>
<?php  exit();
/*
Page: /admin/ppt_main.php
Error: Table 't180.dede_myppt' doesn't exist <br />Error sql: <font color='red'>SELECT COUNT(*) AS dd FROM `dede_myppt` LIMIT 0,1;</font>
Time2019-01-08 10:01:10
*/
?>
<?php  exit();
/*
Page: /admin/ppt_main.php
Error: Table 't180.dede_myppt' doesn't exist <br />Error sql: <font color='red'>Select * from `dede_myppt`  order by aid desc,orderid asc LIMIT 0,20</font>
Time2019-01-08 10:01:10
*/
?>
<?php  exit();
/*
Page: /admin/ppt_add.php
Error: Table 't180.dede_myppttype' doesn't exist <br />Error sql: <font color='red'>SELECT * FROM `dede_myppttype` ORDER BY id DESC</font>
Time2019-01-08 10:01:15
*/
?>
<?php  exit();
/*
Page: /admin/ppt_main.php
Error: Table 't180.dede_myppt' doesn't exist <br />Error sql: <font color='red'>SELECT COUNT(*) AS dd FROM `dede_myppt` LIMIT 0,1;</font>
Time2019-01-08 10:01:40
*/
?>
<?php  exit();
/*
Page: /admin/ppt_main.php
Error: Table 't180.dede_myppt' doesn't exist <br />Error sql: <font color='red'>Select * from `dede_myppt`  order by aid desc,orderid asc LIMIT 0,20</font>
Time2019-01-08 10:01:40
*/
?>
<?php  exit();
/*
Page: /admin/ppt_main.php
Error: Table 't180.dede_myppt' doesn't exist <br />Error sql: <font color='red'>SELECT COUNT(*) AS dd FROM `dede_myppt` LIMIT 0,1;</font>
Time2019-01-08 10:02:20
*/
?>
<?php  exit();
/*
Page: /admin/ppt_main.php
Error: Table 't180.dede_myppt' doesn't exist <br />Error sql: <font color='red'>Select * from `dede_myppt`  order by aid desc,orderid asc LIMIT 0,20</font>
Time2019-01-08 10:02:20
*/
?>
<?php  exit();
/*
Page: /admin/ppttype_main.php
Error: Table 't180.dede_myppttype' doesn't exist <br />Error sql: <font color='red'>Select * From dede_myppttype</font>
Time2019-01-08 10:02:22
*/
?>
<?php  exit();
/*
Page: /admin/ppttype_main.php
Error: Table 't180.dede_myppttype' doesn't exist <br />Error sql: <font color='red'>Select * From dede_myppttype</font>
Time2019-01-08 10:02:32
*/
?>
<?php  exit();
/*
Page: /admin/ppt_main.php
Error: Table 't180.dede_myppt' doesn't exist <br />Error sql: <font color='red'>SELECT COUNT(*) AS dd FROM `dede_myppt` LIMIT 0,1;</font>
Time2019-01-08 10:02:35
*/
?>
<?php  exit();
/*
Page: /admin/ppt_main.php
Error: Table 't180.dede_myppt' doesn't exist <br />Error sql: <font color='red'>Select * from `dede_myppt`  order by aid desc,orderid asc LIMIT 0,20</font>
Time2019-01-08 10:02:35
*/
?>
<?php  exit();
/*
Page: /admin/ppt_add.php
Error: Table 't180.dede_myppttype' doesn't exist <br />Error sql: <font color='red'>SELECT * FROM `dede_myppttype` ORDER BY id DESC</font>
Time2019-01-08 10:02:38
*/
?>
<?php  exit();
/*
Page: /admin/ppt_main.php
Error: Table 't180.dede_myppt' doesn't exist <br />Error sql: <font color='red'>SELECT COUNT(*) AS dd FROM `dede_myppt` LIMIT 0,1;</font>
Time2019-01-08 10:02:56
*/
?>
<?php  exit();
/*
Page: /admin/ppt_main.php
Error: Table 't180.dede_myppt' doesn't exist <br />Error sql: <font color='red'>Select * from `dede_myppt`  order by aid desc,orderid asc LIMIT 0,20</font>
Time2019-01-08 10:02:56
*/
?>
<?php  exit();
/*
Page: /admin/ppttype_main.php
Error: Table 't180.dede_myppttype' doesn't exist <br />Error sql: <font color='red'>Select * From dede_myppttype</font>
Time2019-01-08 10:02:58
*/
?>
<?php  exit();
/*
Page: /admin/ppttype_main.php
Error: Table 't180.dede_myppttype' doesn't exist <br />Error sql: <font color='red'>Select * From dede_myppttype</font>
Time2019-01-08 10:03:05
*/
?>
<?php  exit();
/*
Page: /admin/ppt_main.php
Error: Table 't180.dede_myppt' doesn't exist <br />Error sql: <font color='red'>SELECT COUNT(*) AS dd FROM `dede_myppt` LIMIT 0,1;</font>
Time2019-01-08 10:03:24
*/
?>
<?php  exit();
/*
Page: /admin/ppt_main.php
Error: Table 't180.dede_myppt' doesn't exist <br />Error sql: <font color='red'>Select * from `dede_myppt`  order by aid desc,orderid asc LIMIT 0,20</font>
Time2019-01-08 10:03:24
*/
?>
<?php  exit();
/*
Page: /admin/ppt_add.php
Error: Table 't180.dede_myppttype' doesn't exist <br />Error sql: <font color='red'>SELECT * FROM `dede_myppttype` ORDER BY id DESC</font>
Time2019-01-08 10:03:26
*/
?>
<?php  exit();
/*
Page: /admin/ppt_main.php
Error: Table 't180.dede_myppt' doesn't exist <br />Error sql: <font color='red'>SELECT COUNT(*) AS dd FROM `dede_myppt` LIMIT 0,1;</font>
Time2019-01-08 10:03:41
*/
?>
<?php  exit();
/*
Page: /admin/ppt_main.php
Error: Table 't180.dede_myppt' doesn't exist <br />Error sql: <font color='red'>Select * from `dede_myppt`  order by aid desc,orderid asc LIMIT 0,20</font>
Time2019-01-08 10:03:41
*/
?>
<?php  exit();
/*
Page: /admin/ppt_main.php
Error: Table 't180.dede_myppt' doesn't exist <br />Error sql: <font color='red'>SELECT COUNT(*) AS dd FROM `dede_myppt` LIMIT 0,1;</font>
Time2019-01-08 10:05:22
*/
?>
<?php  exit();
/*
Page: /admin/ppt_main.php
Error: Table 't180.dede_myppt' doesn't exist <br />Error sql: <font color='red'>Select * from `dede_myppt`  order by aid desc,orderid asc LIMIT 0,20</font>
Time2019-01-08 10:05:22
*/
?>
